import type { SessionType, Phase } from "./types"

export type RawSession = {
  week: number
  day: number // 1=Mon, 2=Tue, 3=Wed, 4=Thu, 5=Fri
  type: SessionType
  phase: Phase
  title: string
  duration: string
  workout: string[]
  notes: string[]
}

export const BEGINNER_PLAN_SESSIONS: RawSession[] = [
  // ── WEEK 1 (BASE) ──────────────────────────────────────────────
  {
    week: 1, day: 1, type: "stations", phase: "base",
    title: "Foundation AMRAP",
    duration: "25 Min AMRAP",
    workout: [
      "25 Min AMRAP:",
      "250m Row",
      "20 Air Squats",
      "15 Ring or TRX Row",
      "10 Elevated or Knee Push Ups",
      "50m Farmer Carry",
    ],
    notes: [
      "Goal is to consistently move throughout",
      "Steady pace — if unsure of pacing, go easy first 10 minutes then pick up the pace if desired",
      "Squat to a 12-15\" box if unable to squat below parallel",
      "Elevate Push Ups by having hands on higher surface than feet",
      "Resort to Knee Push Ups if needed",
    ],
  },
  {
    week: 1, day: 2, type: "recovery", phase: "base",
    title: "Aerobic Walk/Jog",
    duration: "20-40 Min",
    workout: [
      "20-40 Min Walk/Jog",
    ],
    notes: [
      "Jog if able",
      "1:00 Jog / 1:00 Walk if needed (or adjust accordingly)",
      "This will vary person to person based on their current ability level",
    ],
  },
  {
    week: 1, day: 3, type: "stations", phase: "base",
    title: "Foundation AMRAP",
    duration: "20 Min AMRAP",
    workout: [
      "20 Min AMRAP:",
      "50ft or 12.5m Sled Push",
      "400m Jog",
      "Single DB Thruster",
    ],
    notes: [
      "Sled Push should be heavy enough where you have to move slowly",
      "400m Jog should feel like recovery",
      "ONE DB: One head of DB in each hand (Squat and Press)",
    ],
  },
  {
    week: 1, day: 4, type: "stations", phase: "base",
    title: "Power Sets",
    duration: "Quality Sets",
    workout: [
      "3-4 Sets:",
      "Goblet Squat x 10",
      "Push Up x 10",
      "Ring or TRX Row x 10",
      "3-4 Sets:",
      "Walking Lunge x 10",
      "DB Shoulder Press x 10",
      "Wall Ball x 10",
    ],
    notes: [
      "Modify Goblet Squat to Air Squat",
      "Modify to Elevated/Knee Push Ups",
      "Adjust body angle on rows to make the movement easier or more challenging (the lower you are, the more challenging)",
      "Ensure full ROM (Rings all the way to chest, Arms fully extended)",
      "Modify walking lunges to assisted lunges (using TRX or rings)",
      "Adjust DB weight as needed",
      "Ensure proper depth on Wall Balls, squat to box if needed",
    ],
  },
  {
    week: 1, day: 5, type: "stations", phase: "base",
    title: "Foundation For Time",
    duration: "45 Min Time Cap",
    workout: [
      "For Time: 3 Rounds",
      "800m-400m-200m Run",
      "30-20-10 DB Shoulder Press",
      "30-20-10 Goblet Squat",
      "30-20-10 Walking Lunge",
      "45 Min Time Cap",
    ],
    notes: [
      "Workout is 3 rounds total, with descending reps each round",
      "DB Shoulder Press should feel like when fresh, but you should need to break at least 1x on the set of 30 and 20",
      "Squat to box if needed",
      "Aim for full ROM on lunges — knee all the way to the ground",
      "Use TRX or low rings for assistance as needed",
    ],
  },

  // ── WEEK 2 (BASE) ──────────────────────────────────────────────
  {
    week: 2, day: 1, type: "stations", phase: "base",
    title: "Foundation Ladder AMRAP",
    duration: "25 Min AMRAP",
    workout: [
      "25 Min AMRAP:",
      "5-10-15-20-25-etc Push Up",
      "Ring/TRX Row (matching reps)",
      "Wall Balls (matching reps)",
      "*200m Run after each round",
    ],
    notes: [
      "Continue up the ladder until you reach 25 minutes",
      "200m Run does not change throughout",
      "Round 1: 5 Push Ups / 5 Ring Row / 5 Wall Balls / 200m Run",
      "Round 2: 10 Push Ups / 10 Ring Rows / 10 Wall Balls / 200m Run — etc",
      "Ensure proper depth is reached on Wall Balls",
      "If able to squat below parallel, start aiming for 3m/10ft for men or 2.7m/9ft for women",
    ],
  },
  {
    week: 2, day: 2, type: "recovery", phase: "base",
    title: "Aerobic Machine Rotation",
    duration: "30-40 Min AMRAP",
    workout: [
      "30-40 Min AMRAP:",
      "3:00 Minute Bike",
      "3:00 Minute Row",
      "3:00 Minute Ski",
    ],
    notes: [
      "Total length is up to you",
      "Pay attention to pace throughout and stay consistent",
      "Conversational pace, but you should break a sweat",
    ],
  },
  {
    week: 2, day: 3, type: "stations", phase: "base",
    title: "Foundation AMRAP",
    duration: "25 Min AMRAP",
    workout: [
      "25 Min AMRAP:",
      "400m Run",
      "10 DB Thruster",
      "8 Burpees",
    ],
    notes: [
      "Go light enough on DB Thrusters where you can do a set of 10 unbroken while reaching below parallel",
      "Aim for a steady pace throughout",
      "Don't waste energy on the burpees — get chest to the ground and get back up any way",
    ],
  },
  {
    week: 2, day: 4, type: "stations", phase: "base",
    title: "Power Conditioning",
    duration: "16 Minutes",
    workout: [
      "For 16 Minutes: Row — Every 2:00 do 10 Push Ups then get back on rower",
      "3x 30 Air Squats",
      "2:00 Minutes Bike",
      "2:00 Minutes Rest after each round",
      "400m Suitcase Carry (Switch arms as needed)",
    ],
    notes: [
      "On a 16 Min Clock, Row. Every 2 Minutes stop to do 10 push ups then get back on the rower",
      "Option to add weight on squats",
      "During the bike, build intensity throughout the 2 Minutes segment",
      "Suitcase Carry: Switch arms as needed but don't come to a complete stop at any point",
    ],
  },
  {
    week: 2, day: 5, type: "stations", phase: "base",
    title: "Foundation For Time",
    duration: "For Time",
    workout: [
      "For Time:",
      "30-20-10 Wall Balls",
      "12.5m/50ft Sled Pull (Arms Only) after each set",
      "*200m Farmer Carry after each round",
    ],
    notes: [
      "Workout is 3 Rounds total, decrease Wall Ball reps each round",
      "Priority is depth of squat on Wall Ball before the height of the ball",
      "Get comfortable pulling the sled — any weight, option to build weight each round",
      "Farmer carry weight should be heavy enough where you need to set the KBs down 1-2x during the 200m",
    ],
  },

  // ── WEEK 3 (BASE) ──────────────────────────────────────────────
  {
    week: 3, day: 1, type: "stations", phase: "base",
    title: "Foundation For Time",
    duration: "For Time",
    workout: [
      "For Time:",
      "25-20-15-10-5 Goblet Squats",
      "30-26-22-18-14 Walking Lunges",
      "*400m Run after each round",
    ],
    notes: [
      "Option to add weight on walking lunges if full ROM is achieved — if adding weight, do Goblet Hold",
      "Reps decrease each round, but the 400m run will remain the same after each round",
      "Round 1: 25 Goblet Squats / 30 Lunges / 400m Run",
      "Round 2: 20 Goblet Squats / 26 Lunges / 400m Run",
      "Round 3: 15 Goblet Squats / 22 Lunges / 400m Run — etc.",
    ],
  },
  {
    week: 3, day: 2, type: "recovery", phase: "base",
    title: "Tempo Run/Jog/Walk",
    duration: "30-45 Minutes",
    workout: [
      "30-45 Minutes Tempo Run/Jog/Walk:",
      "3:00 Minutes Run",
      "2:00 Minutes Jog",
      "1:00 Minute Walk",
    ],
    notes: [
      "Throughout the run, differentiate between 3 paces",
      "This could be different for everyone",
      "Adjust time and intensity domains as needed",
      "The main goal is to have 3 different paces you're working with",
    ],
  },
  {
    week: 3, day: 3, type: "stations", phase: "base",
    title: "Foundation For Time",
    duration: "For Time",
    workout: [
      "For Time:",
      "200m Run",
      "21-18-15-12-9-6-3 DB Push Press",
      "21-18-15-12-9-6-3 DB Front Squat",
      "21-18-15-12-9-6-3 Ring/TRX Row",
    ],
    notes: [
      "7 Rounds total — each round starts with a 200m Run",
      "All other reps decrease by 3 each round",
      "Round 1: 200m Run / 21 Push Press / 21 Front Squat / 21 Row",
      "Round 2: 200m Run / 18 PP / 18 FS / 18 Row — etc.",
    ],
  },
  {
    week: 3, day: 4, type: "stations", phase: "base",
    title: "Power Aerobic AMRAP",
    duration: "40 Min AMRAP",
    workout: [
      "40 Min AMRAP:",
      "3:00 Minutes Row",
      "1:00 Minute Rest",
      "3:00 Minutes Ski",
      "1:00 Minute Rest",
      "3:00 Minutes Bike",
      "1:00 Minute Rest",
    ],
    notes: [
      "Increase intensity through each 3 Minutes effort, treat each as a build",
      "Rest after each machine",
      "Practice getting out of your comfort zone",
    ],
  },
  {
    week: 3, day: 5, type: "stations", phase: "base",
    title: "Foundation RFT",
    duration: "For Time",
    workout: [
      "3 Rounds for Time (RFT):",
      "20 Walking Lunges",
      "15 Push Ups",
      "10 Cal Ski",
      "50ft/12.5m Bear Crawl",
    ],
    notes: [
      "Option to add weight on lunges",
      "Push Ups can be on knees or Hand Release",
    ],
  },

  // ── WEEK 4 (BASE) ──────────────────────────────────────────────
  {
    week: 4, day: 1, type: "race_sim", phase: "base",
    title: "HYROX Complete RFT",
    duration: "For Time",
    workout: [
      "3 RFT:",
      "15 DB Push Press",
      "50ft/12.5m Sled Pull",
      "50ft/12.5m Broad Jump",
      "800m Run",
    ],
    notes: [
      "DB Push Press should be unbroken",
      "Get comfortable pulling the sled — any weight, option to build weight each round",
      "Practice jumping for distance with a two foot take off and two foot landing",
      "Treat 800m Run as a building effort",
    ],
  },
  {
    week: 4, day: 2, type: "engine_builder", phase: "base",
    title: "Sprint Intervals",
    duration: "Run Repeats",
    workout: [
      "1 Mile Jog Warm Up",
      "12 x 100m Run",
      "1:00 Minute Walk between each",
      "1 Mile Jog Cool Down",
    ],
    notes: [
      "See what you're capable of during 100m effort",
      "Build to what feels like a sprint effort",
      "Focus on foot speed and turnover",
    ],
  },
  {
    week: 4, day: 3, type: "stations", phase: "base",
    title: "Foundation RFT",
    duration: "For Time",
    workout: [
      "4 RFT:",
      "400m Ski/Row",
      "400m Run",
      "50ft/12.5m Sled Push",
    ],
    notes: [
      "Focus on steady pace",
      "Build weight on sled throughout — start light and end heavy",
    ],
  },
  {
    week: 4, day: 4, type: "recovery", phase: "base",
    title: "Aerobic Run/Walk",
    duration: "45:00 Minutes",
    workout: [
      "45:00 Minutes Run/Walk",
    ],
    notes: [
      "Run as many minutes as possible",
      "Walk as needed",
    ],
  },
  {
    week: 4, day: 5, type: "stations", phase: "base",
    title: "Foundation Ascending AMRAP",
    duration: "30 Minutes AMRAP",
    workout: [
      "30 Minutes AMRAP:",
      "3-6-9-12-15-etc KB Swing",
      "3-6-9-12-15-etc Goblet Squat",
      "3-6-9-12-15-etc Burpee Broad Jump",
      "*8 Cal hard effort after each round (any machine)",
    ],
    notes: [
      "Work for 30 Minutes straight",
      "Increase reps by 3 each round until 30 Minutes are up",
      "8 Cal effort remains the same throughout after each round",
      "Round 1: 3 KBS / 3 Goblet Squat / 3 Burpee Broad Jump / 8 Cals",
      "Round 2: 6 KBS / 6 Goblet Squat / 6 Burpee Broad Jump / 8 Cals",
    ],
  },

  // ── WEEK 5 (PACE → build) ───────────────────────────────────────
  {
    week: 5, day: 1, type: "stations", phase: "build",
    title: "Foundation For Time",
    duration: "For Time",
    workout: [
      "For Time:",
      "30-20-10 Cal Ski",
      "30-20-10 HR Push Ups",
      "30-20-10 DB Push Press",
      "30-20-10 Goblet Squat",
    ],
    notes: [
      "Modify Push Ups as needed",
      "Choose a DB weight where you have to break the set of 30 and the set of 20 at least once",
      "Use one DB for the Goblet Squat",
    ],
  },
  {
    week: 5, day: 2, type: "engine_builder", phase: "build",
    title: "Engine AMRAPs",
    duration: "5 x 4 Min AMRAP",
    workout: [
      "5 x 4 Min AMRAP (4:00 on / 2:00 off):",
      "200m Run",
      "12 Single DB Thruster",
      "Max Cal Bike",
    ],
    notes: [
      "Each round should build to a 90% effort",
      "Goal is pacing and consistency across rounds",
      "Thrusters should be unbroken",
      "Use 1 DB for Thrusters — one head of DB in each hand",
      "Score = number of cals",
    ],
  },
  {
    week: 5, day: 3, type: "recovery", phase: "build",
    title: "Aerobic Row + Burpees",
    duration: "E3MOM",
    workout: [
      "E3MOM:",
      "4000 Meters Row",
      "3 x Burpee Over Rower (every 3 min)",
    ],
    notes: [
      "Starting at 0:00, do 3 Burpees over the rower",
      "Continue rowing until you reach 4000m while stopping every 3 minutes on the minute to do 3 Burpees over the rower",
    ],
  },
  {
    week: 5, day: 4, type: "engine_builder", phase: "build",
    title: "400m Run Repeats",
    duration: "4 x 400m",
    workout: [
      "4 x 400m Run",
      "2:00 Minutes Rest after each Run",
    ],
    notes: [
      "Each 400m should feel like race pace",
      "Record each 400m split",
      "Log results and note changes in pace, what you are able to hold, etc.",
      "The goal should be to find what pace you can maintain without leaving anything in the tank",
    ],
  },
  {
    week: 5, day: 5, type: "race_sim", phase: "build",
    title: "HYROX Complete For Time",
    duration: "For Time",
    workout: [
      "For Time:",
      "1000 Meters Row/Ski (buy in)",
      "4x: 100ft/25m Sandbag Lunge",
      "4x: 15 Wall Balls (14/10lbs or 6/4kg)",
      "4x: 400 Meters Run",
      "*Accumulate 400ft/100m Sled Push throughout the 4 Rounds",
      "75/50 Cal Bike (cash out)",
    ],
    notes: [
      "The 1000m Row or Ski is to be done once as a buy in",
      "The 75/50 Cal Bike is to be done once as a cash out",
      "Lunges can be done with sandbag or DB on shoulders",
      "The Sled Push can be broken up in any way throughout",
      "Weight on the sled should be AHAP (As Heavy As Possible)",
    ],
  },

  // ── WEEK 6 (PACE → build) ───────────────────────────────────────
  {
    week: 6, day: 1, type: "stations", phase: "build",
    title: "Foundation RFT",
    duration: "For Time",
    workout: [
      "3 RFT:",
      "100m Farmer Carry (53/35lbs or 24/16kg x2)",
      "15 KB Swing (53/35lbs or 24/16kg)",
      "30 Goblet Squat (53/35lbs or 24/16kg)",
      "400 Meters Ski or Row",
    ],
    notes: [
      "Use the same weight throughout: 1 KB for KBS and Goblet Squat / 2 KBs for Farmers Carry",
      "Farmers Carry weight should be heavy enough where you need to set the KBs down 1-2 times",
    ],
  },
  {
    week: 6, day: 2, type: "engine_builder", phase: "build",
    title: "Engine Alt EMOM",
    duration: "20 Minutes Alt EMOM",
    workout: [
      "20 Minutes Alt EMOM (50 sec on / 10 sec off):",
      "Min 1: Goblet Lunge (53/35lbs or 24/16kg)",
      "Min 2: Push Ups / Ring Rows",
      "Min 3: 200 Meters Run",
      "Min 4: Rest",
    ],
    notes: [
      "Alternate movements each minute",
      "Work 50 seconds, use the 10 seconds rest to transition",
      "Do a max set of push ups followed by ring rows in the time remaining",
      "If you are unable to do push ups, do ring rows only",
    ],
  },
  {
    week: 6, day: 3, type: "recovery", phase: "build",
    title: "60 Min Run with Pickups",
    duration: "60 Minutes",
    workout: [
      "60 Minutes Run",
      "Within the 60 Minutes, complete 2x 10 Min Pick Ups",
    ],
    notes: [
      "The 10 Minute Pick Ups can be done at any time",
      "Pace should be lactate threshold — a pace you can maintain for 15 minutes just below the point of discomfort",
      "Walk as needed, but run for as much as possible",
    ],
  },
  {
    week: 6, day: 4, type: "engine_builder", phase: "build",
    title: "Engine Station Intervals",
    duration: "3 Rounds",
    workout: [
      "3 Rounds: 1:00 Minute on / 1:00 Minute off:",
      "Sled Push",
      "Sled Pull",
      "Box Step Over",
      "DB Thruster (35/20lbs or 15/7.5kg x2)",
      "Push Ups",
    ],
    notes: [
      "1 Minute at each movement station",
      "Alternate movements",
      "1 Minute rest between each",
      "You should be working HARD the entirety of the minute",
      "Use 2 DBs for Thrusters",
    ],
  },
  {
    week: 6, day: 5, type: "race_sim", phase: "build",
    title: "HYROX Complete For Time",
    duration: "For Time",
    workout: [
      "For Time:",
      "100/75 Cal Bike or Ski",
      "100 Goblet Squat (53/35lbs or 24/16kg)",
      "1 Mile Run",
      "100 KB Swing (53/35lbs or 24/16kg)",
      "100/75 Cal Bike or Ski",
      "50 Wall Balls (14/10lbs or 6/4kg)",
      "*Every break: complete 100m Farmers Carry",
    ],
    notes: [
      "Every time you break, complete 100m Farmers Carry (only applies for Goblet Squat, KBS, and Wall Balls)",
      "It is considered a break on Goblet Squats if you put the KB down",
      "It is considered a break on KBS and Wall Balls if movement stops",
    ],
  },

  // ── WEEK 7 (PACE → build) ───────────────────────────────────────
  {
    week: 7, day: 1, type: "stations", phase: "build",
    title: "Foundation For Time",
    duration: "For Time",
    workout: [
      "For Time:",
      "30-25-20-15 KB Deadlift (53/35lbs or 24/16kg)",
      "30-25-20-15 Goblet Lunge (53/35lbs or 24/16kg)",
      "30-25-20-15 Wall Ball (14/10lbs or 6/4kg)",
      "100m Farmer Carry (53/35lbs or 24/16kg x2)",
    ],
    notes: [
      "Weight should be the same for KB Deadlift and Farmer Carry",
      "If unable to reach full ROM on Lunges (knee to ground) go unweighted",
      "Prioritize depth on Wall Ball over height",
      "If able to reach below parallel, aim for either a 10/9ft target",
    ],
  },
  {
    week: 7, day: 2, type: "engine_builder", phase: "build",
    title: "Engine Sprint AMRAPs",
    duration: "5 x 3 Min AMRAP",
    workout: [
      "5 x 3 Minutes AMRAP (3:00 on / 3:00 off):",
      "10 DB Thruster (35/20lbs or 15/7.5kg x2)",
      "6 Burpee Broad Jump",
      "Max Cal Bike",
    ],
    notes: [
      "Thrusters should be done in one set",
      "Each round should be a sprint effort",
      "Goal is to find a pace where you can go HARD but maintain while having a 1:1 work/rest ratio",
      "Score = Cals (stay consistent)",
    ],
  },
  {
    week: 7, day: 3, type: "engine_builder", phase: "build",
    title: "800m Run Repeats",
    duration: "4 x 800m",
    workout: [
      "4 x 800m Run at Race Pace",
      "2 Minutes Rest after each",
    ],
    notes: [
      "Record each 800m split",
      "Log results and note changes in pace, what you are able to hold, etc.",
      "The goal should be to find what pace you can maintain without leaving anything in the tank",
    ],
  },
  {
    week: 7, day: 4, type: "stations", phase: "build",
    title: "Foundation Triple AMRAP",
    duration: "30 Minutes",
    workout: [
      "0:00 - 12:00 AMRAP: 15 Wall Balls (14/10lbs) / 12 DB Push Press / 9 Cal Ski",
      "12:00 - 22:00 AMRAP: 50ft/12.5m Sled Push AHAP / 200m Run",
      "22:00 - 30:00 AMRAP: 8 KB Swing / 10 Burpees",
    ],
    notes: [
      "Each AMRAP goes immediately into the next",
      "Sled Push should be AHAP (As Heavy As Possible)",
      "Focus on going right into the run",
      "Rest if needed AFTER the run, not between sled and run",
    ],
  },
  {
    week: 7, day: 5, type: "race_sim", phase: "build",
    title: "HYROX Complete Couplets",
    duration: "For Time",
    workout: [
      "3x: 20/12 Cal Bike / 100ft Sled Push AHAP / 50ft Burpee Broad Jump / 400m Run",
      "Into:",
      "3x: 20/12 Cal Ski / 20 KB Deadlift / 100m Farmer Carry / 20 Wall Balls",
    ],
    notes: [
      "Focus on consistent and steady pace throughout Burpee Broad Jumps",
      "Recover on 400m run as needed",
      "KB Deadlift and Farmers Carry weight should be the same",
      "Go unbroken on Wall Balls",
    ],
  },

  // ── WEEK 8 (PACE → build) ───────────────────────────────────────
  {
    week: 8, day: 1, type: "stations", phase: "build",
    title: "Foundation RFT",
    duration: "For Time",
    workout: [
      "4 RFT:",
      "50ft/12.5m Sled Pull",
      "10 Push Ups",
      "12 DB Push Press (35/20lbs or 15/7.5kg x2)",
      "15 Wall Balls (14/10lbs or 6/4kg)",
      "200m Ski",
    ],
    notes: [
      "Sled Pull: Practice both walk back method and arms only — adjust weight as needed",
      "Wall Balls should be unbroken",
    ],
  },
  {
    week: 8, day: 2, type: "engine_builder", phase: "build",
    title: "Sled + Sprint E2MOM",
    duration: "E2MOM x 8",
    workout: [
      "E2MOM x 8:",
      "50ft/12.5m Sled Push",
      "200m Sprint",
      "Rest in time remaining",
    ],
    notes: [
      "Adjust run distance if unable to get at least 45 seconds rest, OR switch to Ski or Row",
    ],
  },
  {
    week: 8, day: 3, type: "engine_builder", phase: "build",
    title: "400m Run Repeats",
    duration: "6 x 400m",
    workout: [
      "6 x 400m Run",
      "2 Minutes Rest after each",
    ],
    notes: [
      "Challenge yourself to see what you're capable of",
      "Push the pace on these 400m runs",
      "Keep track of your splits and see where you fall off",
      "Goal should be to find your breaking point",
    ],
  },
  {
    week: 8, day: 4, type: "engine_builder", phase: "build",
    title: "Wall Ball + Sprint E4MOM",
    duration: "Every 4:00 x 5",
    workout: [
      "Every 4:00 Minutes x 5:",
      "20 Wall Balls",
      "200m Sprint",
      "Rest in time remaining",
    ],
    notes: [
      "Focus is SPEED",
      "Wall Balls unbroken",
      "No rest — immediately into the 200m Sprint",
    ],
  },
  {
    week: 8, day: 5, type: "race_sim", phase: "build",
    title: "HYROX Complete RFT",
    duration: "For Time",
    workout: [
      "3 RFT:",
      "500m Ski/Row",
      "100ft/25m Goblet Lunge (53/35lbs or 24/16kg)",
      "100m Farmer Carry (53/35lbs or 24/16kg x2)",
      "1000m Run",
      "*Accumulate 350ft/100m Sled Push or Pull throughout",
    ],
    notes: [
      "Finishing is the goal — pace yourself",
      "Sled Push or Sled Pull can be broken up throughout, as long as you reach the designated distance total",
    ],
  },

  // ── WEEK 9 (ACCELERATE → peak) ─────────────────────────────────
  {
    week: 9, day: 1, type: "engine_builder", phase: "peak",
    title: "Run + Station Rounds",
    duration: "5 Rounds",
    workout: [
      "5 Rounds (500m Run + Movement / 2:00 Rest):",
      "Round 1: 500m Run + 500m Ski",
      "Round 2: 500m Run + 30 Burpee Broad Jumps",
      "Round 3: 500m Run + 200m Farmers Carry",
      "Round 4: 500m Run + 50 Sandbag Lunge",
      "Round 5: 500m Run + 75 Wall Balls",
    ],
    notes: [
      "Focus is on run pace",
      "Each round starts with a 500m Run",
      "Take splits of each run — each run should feel like a race pace effort",
      "The movement will change each round — do the movement that corresponds to the round",
    ],
  },
  {
    week: 9, day: 2, type: "stations", phase: "peak",
    title: "Foundation For Time",
    duration: "For Time",
    workout: [
      "For Time:",
      "25-20-15-10-5 Cal Ski",
      "25-20-15-10-5 Goblet Lunge (53/35lbs or 24/16kg)",
      "25-20-15-10-5 DB Push Press (35/20lbs or 15/7.5kg x2)",
      "25-20-15-10-5 DB Front Squat (35/20lbs or 15/7.5kg x2)",
    ],
    notes: [
      "Use 1 KB for Goblet Lunge",
      "Use 2 DBs for Push Press and Front Squat",
      "Steady pace",
      "Break up DB movements as needed",
    ],
  },
  {
    week: 9, day: 3, type: "engine_builder", phase: "peak",
    title: "200m Sprint Repeats",
    duration: "8 x 200m",
    workout: [
      "8 x 200m Run Max Effort",
      "1:30 Minute Rest after each Run",
    ],
    notes: [
      "Each 200m should be a build to sprint",
      "Start at 80% effort for first 100m, build to sprint for the remainder",
      "Record splits",
    ],
  },
  {
    week: 9, day: 4, type: "engine_builder", phase: "peak",
    title: "Bike + Sled + Run Every 5",
    duration: "Every 5:00 x 6",
    workout: [
      "Every 5:00 Minutes x 6:",
      "10/8 Cal Bike",
      "50ft/12.5m Sled Push",
      "200m Run",
      "Rest in time remaining",
    ],
    notes: [
      "Focus on running immediately after the sled push and on speed/turnover of your legs",
      "The runs won't feel fast but see what your legs can do while compromised",
    ],
  },
  {
    week: 9, day: 5, type: "race_sim", phase: "peak",
    title: "HYROX Complete For Time",
    duration: "For Time",
    workout: [
      "For Time:",
      "30-20-10 Cal Bike",
      "30-20-10 Wall Balls (14/10lbs or 6/4kg)",
      "30-20-10 Weighted Walking Lunge",
      "30-20-10 DB Push Press",
      "*800m Run after each round",
    ],
    notes: [
      "Weight lunges any way",
      "Steady pace throughout",
      "Record 800m run splits to see variance per round",
    ],
  },

  // ── WEEK 10 (ACCELERATE → peak) ────────────────────────────────
  {
    week: 10, day: 1, type: "engine_builder", phase: "peak",
    title: "Run + Station Rounds",
    duration: "6 Rounds",
    workout: [
      "6 Rounds (400m Run + 25 Reps / 2:00 Rest):",
      "Round 1: Wall Balls (14/10lbs or 6/4kg)",
      "Round 2: DB Lunge (35/20lbs or 15/7.5kg x2)",
      "Round 3: DB Front Squat (35/20lbs or 15/7.5kg x2)",
      "Rounds 4-6: Repeat",
    ],
    notes: [
      "Focus is on run speed",
      "Record splits for each — try to stay consistent but aim for faster than race pace",
      "Do 25 reps of the corresponding movement immediately after the run",
      "You will go through each movement 2x total",
      "2:00 minutes rest after each round",
    ],
  },
  {
    week: 10, day: 2, type: "race_sim", phase: "peak",
    title: "HYROX Complete RFT",
    duration: "For Time",
    workout: [
      "4 RFT:",
      "1000m Run",
      "100ft/25m Sled Push",
      "40 Walking Lunge",
    ],
    notes: [
      "1000m runs should feel like race effort",
      "Sled Push should be AHAP (As Heavy As Possible)",
      "Lunges should be body weight only — option to add weight if desired",
    ],
  },
  {
    week: 10, day: 3, type: "engine_builder", phase: "peak",
    title: "400m Run Repeats Hard",
    duration: "6 x 400m",
    workout: [
      "6 x 400m Run HARD",
      "2:00 Minutes rest after each Run",
    ],
    notes: [
      "Don't hold back on these 400m runs",
      "See where you can hang and where you fall off",
      "Record Splits",
    ],
  },
  {
    week: 10, day: 4, type: "engine_builder", phase: "peak",
    title: "Engine Bike/BBJ/Wall Ball",
    duration: "5 Rounds",
    workout: [
      "5 Rounds:",
      "10/8 Cal Bike",
      "8 Burpee Broad Jumps",
      "15 Wall Balls",
      "10/8 Cal Bike",
      "1:00 Minute Rest",
    ],
    notes: [
      "Each round is an 80-100% effort",
      "Wall Balls should be unbroken",
      "PUSH on the bike but pay attention to RPM and don't fall off",
      "Adjust weight as needed throughout",
    ],
  },
  {
    week: 10, day: 5, type: "race_sim", phase: "peak",
    title: "HYROX Complete For Time",
    duration: "For Time",
    workout: [
      "For Time:",
      "1000m Ski",
      "1000m Row",
      "1000m Run",
      "75 Goblet Squat (53/35lbs or 24/16kg)",
      "75 KB Swing (53/35lbs or 24/16kg)",
      "50 Headcutters",
      "50 Burpee Broad Jump",
      "50 Cal Bike",
      "100m Sled Push",
    ],
    notes: [
      "Partition reps in any way, in any order",
      "Goal is completion in 60 minutes or less",
      "Use the same KB weight throughout",
    ],
  },

  // ── WEEK 11 (PRIME → peak) ─────────────────────────────────────
  {
    week: 11, day: 1, type: "race_sim", phase: "peak",
    title: "HYROX Complete RFT",
    duration: "For Time",
    workout: [
      "3 RFT:",
      "20/12 Cal Bike",
      "400m Run",
      "30 Sandbag Lunge",
      "500m Ski",
      "100m Farmers Carry (53/35lbs or 24/16kg x2)",
    ],
    notes: [
      "Watch RPM on bike and stay consistent",
      "If no sandbag, use DB or Barbell on back",
      "100m Farmer Carry should be unbroken",
    ],
  },
  {
    week: 11, day: 2, type: "stations", phase: "peak",
    title: "Foundation AMRAP",
    duration: "25 Min AMRAP",
    workout: [
      "25 Min AMRAP:",
      "100ft/25m Sled Push",
      "500m Run or Row",
      "20 Wall Balls (14/10lbs or 6/4kg)",
    ],
    notes: [
      "This should be a moderate Recovery Pace",
      "Stay steady and consistent",
      "Run or Row, depending on what you're feeling for the day",
    ],
  },
  {
    week: 11, day: 3, type: "engine_builder", phase: "peak",
    title: "800m Run Repeats",
    duration: "4 x 800m",
    workout: [
      "4 x 800m Run at Race Pace",
      "2:00 Minutes Rest after each Run",
    ],
    notes: [
      "These should feel fresh",
      "Run at what you feel is race pace",
      "Record Splits",
    ],
  },
  {
    week: 11, day: 4, type: "recovery", phase: "peak",
    title: "Run with Pickups",
    duration: "40-50 Minutes",
    workout: [
      "40-50 Minutes Run",
      "6 x 1:00 Minute Pickup",
      "2 Minutes Easy between each Pickup",
    ],
    notes: [
      "Complete 6 x 1 Minute Pick Ups / 2 Minutes Easy at some point during the run",
      "The pickup can be hard or moderate depending on how you're feeling",
    ],
  },
  {
    week: 11, day: 5, type: "race_sim", phase: "peak",
    title: "HYROX Race Simulation",
    duration: "5 Rounds",
    workout: [
      "5 Rounds:",
      "800m Run",
      "*Choose 5 HYROX Stations you'd like to run through",
    ],
    notes: [
      "Choose any 5 HYROX Race Movement Standards",
      "Go in race order",
      "Goal should be race pace or race feel",
    ],
  },

  // ── WEEK 12 (RACE → taper) ─────────────────────────────────────
  {
    week: 12, day: 1, type: "stations", phase: "taper",
    title: "Foundation RFT",
    duration: "Moderate Pace",
    workout: [
      "4 RFT:",
      "500m Row",
      "20 KB Deadlift (53/35lbs or 24/16kg x2)",
      "100m Farmer Carry (53/35lbs or 24/16kg x2)",
      "50ft/12.5m Sled Pull",
    ],
    notes: [
      "Moderate Pace",
      "Practice different types of sled pull technique: arms only, full body, walk back",
      "Go lighter on KB Deadlift and Farmer Carry if you want to lower the intensity",
    ],
  },
  {
    week: 12, day: 2, type: "recovery", phase: "taper",
    title: "Aerobic Machine AMRAP",
    duration: "40 Min AMRAP",
    workout: [
      "40 Min AMRAP:",
      "Machine Cals: 10-15-20-25-30-etc",
      "Rotate between Ski/Bike + Row",
    ],
    notes: [
      "Moderate Pace",
      "Go by feel — if you feel good and want to add intensity",
      "Do the first 10 Cals of each movement as a sprint or hard effort followed by recovery",
    ],
  },
  {
    week: 12, day: 3, type: "engine_builder", phase: "taper",
    title: "Sprint + BBJ Intervals",
    duration: "6 Rounds",
    workout: [
      "6x:",
      "200m Build to sprint",
      "6 Burpee Broad Jump",
      "1:00 Minute Rest",
    ],
    notes: [
      "These should feel fresh",
      "Build to a sprint",
      "Adjust the number of Burpee Broad Jumps as desired",
    ],
  },
  {
    week: 12, day: 4, type: "recovery", phase: "taper",
    title: "Easy Run",
    duration: "45 Minutes",
    workout: [
      "45 Minutes Easy Run",
    ],
    notes: [
      "This should be a \"Feel good\" Jog",
      "Option to switch to Row, Ski or Bike",
    ],
  },
  {
    week: 12, day: 5, type: "recovery", phase: "taper",
    title: "Shake Out Run",
    duration: "20-30 Minutes",
    workout: [
      "OPTIONAL: 20-30 Minutes Shake Out Run",
    ],
    notes: [
      "Totally optional depending on how you're feeling",
      "Only if you think your legs will benefit from a quick/easy run",
      "Don't stress about getting it in",
    ],
  },
]

// Source: docs/hyrox-source/open.md
export const OPEN_PLAN_SESSIONS: RawSession[] = [
  // ── WEEK 1 (BASE) ──────────────────────────────────────────────
  {
    week: 1, day: 1, type: "stations", phase: "base",
    title: "Open Foundation",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "500m Row",
      "KB Deadlifts (53/35lbs or 24/16kg x 2)",
      "20 Wall Balls (14/10lbs or 6/4kg)",
      "100m Farmer Carry (53/35lbs or 24/16kg x 2)",
    ],
    notes: [
      "Pay attention to pace on row, stay consistent",
      "KB Deadlifts should be able to be done in 1 set",
      "Wall balls should be unbroken",
      "Go heavier on Farmer Carry if desired",
    ],
  },
  {
    week: 1, day: 2, type: "recovery", phase: "base",
    title: "Open Aerobic",
    duration: "45-60 Min Run",
    workout: [
      "45-60 Min Run",
      "Finish with 6 x 20 Second Strides",
    ],
    notes: [
      "Conversational Pace",
      "During strides, start slow and build to sprint effort for the last 6-10 steps",
    ],
  },
  {
    week: 1, day: 3, type: "stations", phase: "base",
    title: "Open Foundation",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "50ft/12.5 Sled Push - AHAP",
      "400m Run",
      "15 Headcutters (53/35lbs or 24/16kg)",
    ],
    notes: [
      "AHAP = As heavy as possible",
      "Option to modify Headcutters to Wall Balls or Goblet Squat as needed",
    ],
  },
  {
    week: 1, day: 4, type: "stations", phase: "base",
    title: "Open Power",
    duration: "Quality Sets",
    workout: [
      "4x",
      "Goblet Squat x 20",
      "DB Bench Press x 15",
      "Ring/TRX Rows x Failure",
      "Max Bike Sprint x 30 sec",
      "1:30 Minutes Rest",
      "4x",
      "Split Squats x 10 Each Leg",
      "DB Shoulder Press x 15",
      "DB Curls x 12 Each",
      "200m Loaded Carry (100m Front Rack/100m Farmer Carry)",
    ],
    notes: [
      "This is for quality, not for time",
      "Choose weights where the last 3 reps are very challenging",
      "If unable to do chin ups, do TRX or Ring Rows",
      "Movements are meant to be done one after the other with minimal rest. Rest 90 seconds after each round",
      "On the loaded carry, use the same weight for both. Hold KBs or DBs in front rack position for the first 100m, then switch to a farmer carry hold for the second 100m",
      "Rest as needed throughout",
    ],
  },
  {
    week: 1, day: 5, type: "stations", phase: "base",
    title: "Open Foundation",
    duration: "For Time: 3 Rounds",
    workout: [
      "For Time: 3 Rounds",
      "800m-400m-200m Run",
      "30-20-10",
      "Alt DB Snatch",
      "Goblet Squat",
      "Goblet Lunge",
      "50ft/12.5 Sled Push after each round",
    ],
    notes: [
      "Workout is 3 rounds total, with descending reps each round (Sled Push weight remains the same throughout)",
      "Round 1: 800m Run and 30 reps of each mvmt",
      "Round 2: 400m Run and 20 reps of each mvmt",
      "Round 3: 200m Run and 10 reps of each mvm",
    ],
  },
  // ── WEEK 2 (BASE) ──────────────────────────────────────────────
  {
    week: 2, day: 1, type: "stations", phase: "base",
    title: "Open Foundation",
    duration: "25 Min AMRAP",
    workout: [
      "25 Min AMRAP:",
      "5-10-15-20-25-etc",
      "KB Deadlift (53/35lbs or 24/16kg x 2)",
      "Goblet Lunge (50/35lbs or 22.5/15kg)",
      "10-20-30-40-50-etc",
      "Wall Balls (14/10lbs or 6/4kg)",
      "*200m Run after each round",
    ],
    notes: [
      "Continue up the ladder until you reach 25 minutes",
      "200m Run does not change throughout",
      "Round 1: 5 KB DL/5 FR Lunge/10 Wallballs/200m Run",
      "Round 2: 10 KB DL/10 FR Lunge/20 Wallballs/200m Run",
      "Round 3: 15 KB DL/15 FR Lunge/30 Wallballs/200m Run",
      "...etc",
    ],
  },
  {
    week: 2, day: 2, type: "recovery", phase: "base",
    title: "Open Aerobic",
    duration: "50-60 Min AMRAP",
    workout: [
      "50-60 Min AMRAP:",
      "5:00 Minutes Bike",
      "5:00 Minutes Row",
      "5:00 Minutes Ski",
      "All at an easy yet consistent pace",
    ],
    notes: [
      "Work for 50-60 minutes total",
      "Pay attention to pace throughout and stay consistent",
      "Conversational pace, but you should break a sweat",
    ],
  },
  {
    week: 2, day: 3, type: "stations", phase: "base",
    title: "Open Foundation",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "400m Run",
      "10 DB Thruster (35/20lbs or 15/10kg x 2)",
      "12 Burpee Broad Jumps",
    ],
    notes: [
      "DB Thrusters should be unbroken",
      "Plant hands close to feet in order to maintain the Burpee Broad Jump standard",
    ],
  },
  {
    week: 2, day: 4, type: "stations", phase: "base",
    title: "Open Power",
    duration: "Quality Sets",
    workout: [
      "100 Cal Row",
      "Every 2:00 10 x Bench Press",
      "4x",
      "25 Back Squats (Unbroken)",
      "10 Cal Bike Sprint",
      "2:00 Minutes Rest after each round",
      "400m Suitcase Carry (Switch arms as needed)",
    ],
    notes: [
      "100 Cal Row should be a moderate pace",
      "Stop every 2 Minutes and complete 10 x Bench Press. (Build each round)",
      "Back squats should be unbroken, build each round",
      "Go immediately into the 10 Cal Bike Sprint",
      "Suitcase Carry: Switch arms as needed but don't come to a complete stop at any point",
    ],
  },
  {
    week: 2, day: 5, type: "stations", phase: "base",
    title: "Open Foundation",
    duration: "For Time",
    workout: [
      "For Time:",
      "30-20-10",
      "Alt DB Snatch",
      "50ft Sled Pull (Arms Only)",
      "*200m Farmer Carry after each round (53/35lbs or 24/16kg)",
    ],
    notes: [
      "3 Rounds total",
      "DB Snatch reps decrease each round",
      "Sled Pull should be AHAP, no walking back",
      "Farmer Carry should be heavy enough where you need to break at least 1 time during each 200m",
    ],
  },
  // ── WEEK 3 (BASE) ──────────────────────────────────────────────
  {
    week: 3, day: 1, type: "stations", phase: "base",
    title: "Open Foundation",
    duration: "For Time",
    workout: [
      "For Time:",
      "50-40-30-20-10",
      "Wall Balls",
      "21-18-15-12-9",
      "KBS (53/35lbs or 24/16kg)",
      "*400m Run after each round",
      "*Every time you break on Wall Balls, FOUNDATION 10 Burpees",
    ],
    notes: [
      "5 Rounds, reps decrease each round",
      "400m Run remains the same",
      "A break on Wall Balls is any time movement stops or ball drops",
      "Round 1: 50 Wall Balls/21 KBS/400m Run",
      "Round 2: 40 Wall Balls/18 KBS/400m Run",
      "Round 3: 30 Wall Balls/15 KBS/400m Run—etc",
      "(+ penalty burpees if you break on wall balls)",
    ],
  },
  {
    week: 3, day: 2, type: "recovery", phase: "base",
    title: "Open Aerobic",
    duration: "50 Minutes Progressive Run",
    workout: [
      "50 Minutes Progressive Run",
      "Increase pace every 10 Mins so at least 10 Mins faster / hardest effort",
    ],
    notes: [
      "If you have a GPS watch with your pace, use it and take splits to record data",
      "The last 10 mins should feel harder than race effort",
    ],
  },
  {
    week: 3, day: 3, type: "stations", phase: "base",
    title: "Open Foundation",
    duration: "For Time",
    workout: [
      "For Time:",
      "100m Farmer Carry",
      "21-18-15-12-9-6-3",
      "DB Hang Clean",
      "DB Push Press",
      "DB Front Squat (35/20lbs or 15/10kg x 2)",
    ],
    notes: [
      "7 Rounds total",
      "Each round starts with a 100m Farmer Carry",
      "This will be grippy!",
      "Use the same weight throughout for all movements",
    ],
  },
  {
    week: 3, day: 4, type: "stations", phase: "base",
    title: "Open Power",
    duration: "Quality Sets",
    workout: [
      "4x",
      "Barbell RDL x 8",
      "Split Squat Jump x 10",
      "100ft Sled Sprint",
      "1:30 Minutes Rest",
      "4x",
      "Bench Press x 20",
      "KBS x 20",
      "10 Cal Ski Sprint",
      "1:30 Minutes Rest",
    ],
    notes: [
      "For quality, not for time",
      "Build RDL weight",
      "Sled Push: Use ½ \"Normal\" weight (What you normally use in training)",
      "Rest after each complete round",
      "Bench Press: Build each round",
      "Movements should be back to back with rest after each round",
    ],
  },
  {
    week: 3, day: 5, type: "stations", phase: "base",
    title: "Open Foundation",
    duration: "4RFT",
    workout: [
      "4RFT:",
      "20 DB Front Rack Lunge (50/35lbs or 22.5/15kg)",
      "15 HR Push Ups",
      "10 Cal Ski",
      "100ft/25m Bear Crawl",
    ],
    notes: [
      "Lunges should be unbroken",
      "Push Ups should be STRICT: No sagging core, hips and shoulders in line",
      "HR = Hand Release at bottom of push up",
      "Bear Crawl: Hands and feet only touching the ground",
    ],
  },
  // ── WEEK 4 (BASE) ──────────────────────────────────────────────
  {
    week: 4, day: 1, type: "stations", phase: "base",
    title: "Open Foundation",
    duration: "For Time",
    workout: [
      "For Time:",
      "30-20-10",
      "DB Push Press (35/20lbs or 15/10kg x 2)",
      "50ft-50ft-50ft (12.5)",
      "Sled Pull",
      "30-20-10",
      "Alt DB Snatch",
      "*800m Run after each round",
    ],
    notes: [
      "3 Rounds, decrease reps EXCEPT Sled Pull and 800m Run remain the same",
      "Round 1: 30 DB Push Press/50ft Sled Pull/30 Alt DB Snatch/800m Run",
      "Round 2: 20 DB Push Press/50ft Sled Pull/20 Alt DB Snatch/800m Run",
      "...etc",
    ],
  },
  {
    week: 4, day: 2, type: "recovery", phase: "base",
    title: "Open Aerobic",
    duration: "1 Mile Run Warm Up",
    workout: [
      "1 Mile Run Warm Up",
      "12 x 200m at 90% effort",
      "1:00 Minute Easy Jog between",
      "1 Mile Cool Down",
    ],
    notes: [
      "Each effort should be a build to 90% effort",
      "Focus on quick turnover",
      "Recovery job should be super slow/easy if not walk",
    ],
  },
  {
    week: 4, day: 3, type: "stations", phase: "base",
    title: "Open Foundation",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "400m Ski/Row",
      "400m Run",
      "100ft/25m Sled Push AHAP",
    ],
    notes: [
      "Ski/Row: Moderate Pace",
      "Run: Race Pace",
      "Sled Push: Sled should be AHAP (As Heavy As Possible)",
    ],
  },
  {
    week: 4, day: 4, type: "stations", phase: "base",
    title: "Open Power",
    duration: "Quality Sets",
    workout: [
      "4x",
      "Split Squat x 10 each",
      "KB Deadlift x 20",
      "DB Bench Press x 20",
      "60 Sec Rest",
      "4x",
      "10 Cal Ski",
      "10-20 Ring Rows",
      "50ft or 12.5m Sled Pull",
      "60 Sec Rest",
    ],
    notes: [
      "For Quality, not for time",
      "Split Squat: Complete all 10 reps on one leg before switching to the other. Feet should remain planted in lunge for entirety of set",
      "KB Deadlift and DB Bench Press should be unbroken",
      "Sled Pull should be arms only",
      "Rest at the end of each round",
    ],
  },
  {
    week: 4, day: 5, type: "stations", phase: "base",
    title: "Open Foundation",
    duration: "30 Minutes AMRAP",
    workout: [
      "30 Minutes AMRAP:",
      "3-6-9-12-15-etc",
      "KBS (53/35lbs or 24/16kg)",
      "Headcutter",
      "Burpee Broad Jump",
      "*10 Cal Sprint after each round (Any machine)",
    ],
    notes: [
      "Continue ascending rep ladder until 30:00 Minutes are up",
      "Each movement (except for cals) should increase by 3 reps each round",
      "Each round should end with a 10 Cal Sprint",
      "Round 1: 3 KBS/3 Headcutter/3 Burpee Broad Jump/10 Cal Sprint",
      "Round 2: 6 KBS/6 Headcutter/6 Burpee Broad Jump/10 Cal Sprint",
      "Round 3: 9 KBS/9 Headcutter/9 Burpee Broad Jump/10 Cal Sprint",
      "...etc",
    ],
  },
  // ── WEEK 5 (BUILD) ──────────────────────────────────────────────
  {
    week: 5, day: 1, type: "stations", phase: "build",
    title: "Open Foundation",
    duration: "For Time",
    workout: [
      "For Time:",
      "30-25-20-15-10",
      "Cal Ski",
      "HR Push Ups",
      "DB Push Press",
      "KB Deadlift",
    ],
    notes: [
      "Push Ups should be STRICT: No sagging core, hips and shoulders in line",
      "HR = Hand Release at bottom of push up",
      "Option to go heavier on KB Deadlift",
      "Expect to break up sets",
    ],
  },
  {
    week: 5, day: 2, type: "engine_builder", phase: "build",
    title: "Open Engine",
    duration: "5 x 4 Min AMRAP",
    workout: [
      "5 x 4 Min AMRAP",
      "4:00 Minutes on/2:00 Minutes off",
      "400m Run",
      "12 Headcutters (53/35lbs or 24/16kg)",
      "Max Cal Bike",
    ],
    notes: [
      "Each round should be a 90% effort",
      "Goal is pacing and consistency across rounds",
      "Headcutters should be unbroken",
      "Score = number of cals",
    ],
  },
  {
    week: 5, day: 3, type: "recovery", phase: "build",
    title: "Open Aerobic",
    duration: "5000 Meters Row",
    workout: [
      "5000 Meters Row",
      "E2OM:",
      "4000 Meters Row",
      "5 x Burpee Over Rower",
    ],
    notes: [
      "Starting at 0:00, complete 5 Burpees over the rower",
      "Continue rowing until you reach 5000m while stopping every 2 minutes on the minute to do 5 Burpees over the rower",
    ],
  },
  {
    week: 5, day: 4, type: "engine_builder", phase: "build",
    title: "Open Engine",
    duration: "6 x 400m Run",
    workout: [
      "6 x 400m Run",
      "2:00 Minutes Rest after each Run",
    ],
    notes: [
      "Each 400m should feel like race pace",
      "Record each 400m split",
      "Log results and note changes in pace, what you are able to hold, etc.",
      "The goal should be to find what pace you can maintain without leaving anything in the tank",
    ],
  },
  {
    week: 5, day: 5, type: "race_sim", phase: "build",
    title: "Open Complete",
    duration: "For Time",
    workout: [
      "For Time:",
      "1000 Meters Row/Ski",
      "4x",
      "150ft/25m Sandbag Lunge (35/20lbs or 15/10kg x 2)",
      "25 Wall Balls (14/10lbs or 6/4 kg)",
      "400m Run",
      "100/75 Cal Bike",
      "*Accumulate 350ft or 100m Sled Push throughout the 4 rounds",
    ],
    notes: [
      "The 1000m Row or Ski is to be done once as a buy in",
      "The 100/75 Cal Bike is to be done once as a cash out",
      "DB Lunges can be done as Front Rack or to your sides",
      "The Sled Push can be broken up in any way throughout",
      "Weight on the sled should be AHAP (As Heavy As Possible)",
    ],
  },
  // ── WEEK 6 (BUILD) ──────────────────────────────────────────────
  {
    week: 6, day: 1, type: "stations", phase: "build",
    title: "Open Foundation",
    duration: "3 RFT",
    workout: [
      "3 RFT:",
      "200m Farmer Carry (53/35lbs or 24/16 kg x 2)",
      "15 KBS (53/35lbs or 24/16 kg)",
      "30 Goblet Squat (53/35lbs or 24/16 kg)",
      "400 Meters Ski or Row",
    ],
    notes: [
      "Use the same weight throughout: 1 KB for KBS and Goblet Squat/2 KBs for Farmers Carry",
      "Farmers Carry weight should be heavy enough where you need to set the KBs down 1-2 times",
    ],
  },
  {
    week: 6, day: 2, type: "engine_builder", phase: "build",
    title: "Open Engine",
    duration: "20 Minutes Alt EMOM (50 sec on/10 sec off)",
    workout: [
      "20 Minutes Alt EMOM (50 sec on/10 sec off)",
      "Goblet Lunge (53/35lbs or 24/16 kg)",
      "Strict Pull Ups / Push Ups",
      "200 Meters Run",
      "Rest",
    ],
    notes: [
      "Alternate movements each minute",
      "Work 50 seconds, use the 10 seconds rest to transitioning",
      "Do a max set of push ups followed by ring rows in the time remaining",
      "If you are unable to do push ups, do ring rows only",
    ],
  },
  {
    week: 6, day: 3, type: "recovery", phase: "build",
    title: "Open Aerobic",
    duration: "60 Minutes Run",
    workout: [
      "60 Minutes Run",
      "Within the 60 Minutes window, complete 2x 15 Min Pick Ups",
    ],
    notes: [
      "The 15 Minutes Pick Ups can be done at any time",
      "Pace should be lactate threshold hold, or a pace you can maintain for 15 minutes just below the point of discomfort",
    ],
  },
  {
    week: 6, day: 4, type: "engine_builder", phase: "build",
    title: "Open Engine",
    duration: "3 Rounds: 1:00 Minute on/1:00 Minute off",
    workout: [
      "3 Rounds: 1:00 Minute on/1:00 Minute off",
      "Sled Push",
      "Sled Pull",
      "DB Box Over",
      "Headcutters (53/35lbs or 24/16 kg)",
      "Push Ups",
    ],
    notes: [
      "1 Minute at each movement station",
      "Alternate movements",
      "1 Minute rest between each",
      "You should be working HARD the entirety of the minute",
    ],
  },
  {
    week: 6, day: 5, type: "race_sim", phase: "build",
    title: "Open Complete",
    duration: "For Time",
    workout: [
      "For Time:",
      "100/75 Cal Bike or Ski",
      "100 Back Squats (105/75lbs or 50/35kg)",
      "1 Mile Run",
      "100 KBS (35/25lbs or 15/12.5kg)",
      "100/75 Cal Bike or Ski",
      "100 Headcutters (35/25lbs or 15/12.5kg)",
      "*Every break FOUNDATION 100m Farmer Carry (53/35lbs or 24/16 kg x 2)",
    ],
    notes: [
      "Back Squats: Choose a weight that you can get at least a set of 30 unbroken while fresh",
      "KBS and Headcutter weight should be slightly lighter than usual",
      "Every time you break, complete 100m Farmer Carry",
      "(Only applies for back squat, KBS, and Headcutters",
      "It is considered a break on back squats if you put the bar down",
      "It is considered a break on KBS and Headcutters if movement stops",
    ],
  },
  // ── WEEK 7 (BUILD) ──────────────────────────────────────────────
  {
    week: 7, day: 1, type: "stations", phase: "build",
    title: "Open Foundation",
    duration: "For Time",
    workout: [
      "For Time:",
      "30-25-20-15",
      "KB Deadlift (53/35lbs or 24/16kg)",
      "DB/KB Lunges (35/25lbs or 15/12.5kg x 2)",
      "Headcutters (53/35lbs or 24/16kg)",
      "100m Farmer Carry (53/35lbs or 24/16kg x 2)",
    ],
    notes: [
      "Weight should be the same for KB Deadlift and Farmer Carry",
      "Lunges can be done with a front rack hold or to the sides",
      "Headcutter: Use 1 of the KBs you used for the Farmer Carry and Deadlift",
    ],
  },
  {
    week: 7, day: 2, type: "engine_builder", phase: "build",
    title: "Open Engine",
    duration: "5 x 3 Minutes AMRAP: 3:00 on/3:00 off",
    workout: [
      "5 x 3 Minutes AMRAP: 3:00 on/3:00 off",
      "10 Devil Press (35/20lbs or 15/7.5 kg x 2)",
      "6 Burpee Box Jump Over",
      "Max Cal Bike",
    ],
    notes: [
      "Devils Press should be done in 1:30 Minutes or less (Lower reps if needed)",
      "Each round should be a sprint effort",
      "Goal is to find a pace where you can go HARD but maintain while having a 1:1 work/rest ratio",
      "Score = cals (Stay consistent)",
    ],
  },
  {
    week: 7, day: 3, type: "engine_builder", phase: "build",
    title: "Open Engine",
    duration: "4 x 1000m Run at Race Pace",
    workout: [
      "4 x 1000m Run at Race Pace",
      "2:00 Minutes Rest after each Run",
    ],
    notes: [
      "Record each 1000m Split",
      "Log results and note changes in pace, what you are able to hold, etc.",
      "The goal should be to find what pace you can maintain without leaving anything in the tank",
    ],
  },
  {
    week: 7, day: 4, type: "stations", phase: "build",
    title: "Open Foundation",
    duration: "0:00 - 12:00 Minutes AMRAP",
    workout: [
      "0:00 - 12:00 Minutes AMRAP:",
      "15 Wall Balls (20/14lbs)",
      "12 DB Push Press (53/35lbs or 24/16kg x 2)",
      "9 Cal Ski",
      "12:00 - 22:00 // AMRAP:",
      "50ft/12.5 Sled Push AHAP",
      "200m Run",
      "22:00 - 30:00 // AMRAP:",
      "8 Headcutters (70/35lbs or 32/16kg)",
      "10 Burpees",
    ],
    notes: [
      "Each AMRAP goes immediately into the next",
      "Sled Push should be As Heavy As Possible",
      "Focus on going right into the run",
      "Headcutters should be done unbroken",
    ],
  },
  {
    week: 7, day: 5, type: "race_sim", phase: "build",
    title: "Open Complete",
    duration: "3x",
    workout: [
      "3x",
      "30/20 Cal Bike",
      "100ft Sled Push AHAP",
      "50ft/12.5m BBJ",
      "400m Run",
      "Into:",
      "3x",
      "30/20 Cal Ski",
      "20 KB Deadlift (53/35lbs or 24/16kg x 2)",
      "100m Farmer Carry (53/35lbs or 24/16kg x 2)",
      "25 Wall Balls (14/10lbs or 6/4kg)",
    ],
    notes: [
      "Focus on consistent and steady pace throughout BBJ",
      "Recover on run as needed",
      "KB Deadlift and Farmers Carry weight should be the same",
      "Go unbroken on Wall Balls",
    ],
  },
  // ── WEEK 8 (BUILD) ──────────────────────────────────────────────
  {
    week: 8, day: 1, type: "stations", phase: "build",
    title: "Open Foundation",
    duration: "5 RFT",
    workout: [
      "5 RFT:",
      "50ft/12.5m Sled Pull",
      "12 Alt DB Snatch (35/20lbs or 15/7.5kg x 2)",
      "25 Wall Balls (14/10lbs or 6/4 kg)",
      "200m Ski",
    ],
    notes: [
      "Sled Pull: Practice both walk back method and arms only. Adjust weight as needed",
      "Wall Balls should be unbroken",
    ],
  },
  {
    week: 8, day: 2, type: "engine_builder", phase: "build",
    title: "Open Engine",
    duration: "E2MOM x 10",
    workout: [
      "E2MOM x 10",
      "50ft/12.5m Sled Push",
      "200m Sprint",
      "Rest in time remaining",
    ],
    notes: [
      "The focus is getting used to running immediately after the sled",
      "Run what \"feels\" like a sprint after the sled push",
    ],
  },
  {
    week: 8, day: 3, type: "engine_builder", phase: "build",
    title: "Open Engine",
    duration: "8 x 400m Run",
    workout: [
      "8 x 400m Run",
      "2:00 Minutes Rest after each Run",
    ],
    notes: [
      "Challenge yourself to see what you're capable of",
      "Push the pace on these 400m runs",
      "Keep track of your splits and see where you fall off",
      "Goal should be to find your breaking point",
    ],
  },
  {
    week: 8, day: 4, type: "engine_builder", phase: "build",
    title: "Open Engine",
    duration: "Every 3:30 Minutes x 5",
    workout: [
      "Every 3:30 Minutes x 5",
      "30 Wall Balls",
      "200m Sprint",
      "Rest in time remaining",
    ],
    notes: [
      "Focus is SPEED",
      "Wall Balls unbroken",
      "No rest, immediately into the 200m Sprint",
    ],
  },
  {
    week: 8, day: 5, type: "race_sim", phase: "build",
    title: "Open Complete",
    duration: "3 RFT",
    workout: [
      "3 RFT:",
      "500m Ski/Row",
      "100ft/25m KB Lunge (35/20lbs or 16/8kg x 2)",
      "100m Farmer Carry (53/35lbs or 24/16kg x 2)",
      "1000m Run",
      "*Accumulate 350ft or 100m Sled Push or Pull throughout",
    ],
    notes: [
      "Lunges can be front rack hold or KB/DBs to your sides",
      "Option to use one KB/DB in Goblet Hold",
      "Sled Push or Pull can be broken up throughout, as long as you reach the designated distance total",
    ],
  },
  // ── WEEK 9 (PEAK) ──────────────────────────────────────────────
  {
    week: 9, day: 1, type: "engine_builder", phase: "peak",
    title: "Open Engine",
    duration: "5 Rounds",
    workout: [
      "5 Rounds:",
      "500m Run",
      "*Movement",
      "500 Run",
      "2:00 Minutes Rest",
      "*Round 1: 500m Ski",
      "*Round 2: 40 BBJs",
      "*Round 3: 200m Farmers Carry (53/35lbs or 24/14kg x 2)",
      "*Round 4: 80 Sandbag Lunge (20/10kg)",
      "*Round 5: 100 Wall Balls (14/10lbs or 6/4kg)",
    ],
    notes: [
      "Focus is on run pace",
      "Each round starts with a 500m Run",
      "Take splits of each run",
      "Each run should feel like a race pace effort",
      "The movement will change each round",
      "Do the movement that corresponds to the round",
    ],
  },
  {
    week: 9, day: 2, type: "race_sim", phase: "peak",
    title: "Open Complete",
    duration: "For Time",
    workout: [
      "For Time:",
      "50-40-30-20-10",
      "Cal Ski",
      "DB Push Press (53/35lbs or 24/16kg)",
      "Alt DB Snatch (35/20lbs or 15/7.5kg x 2)",
      "DB Front Squat (35/20lbs or 15/7.5kg x 2)",
    ],
    notes: [
      "Steady Pace",
      "Break up DB movements as needed",
    ],
  },
  {
    week: 9, day: 3, type: "engine_builder", phase: "peak",
    title: "Open Engine",
    duration: "8 x 200m Run Max Effort",
    workout: [
      "8 x 200m Run Max Effort",
      "90 Sec rest after each",
    ],
    notes: [
      "Each 200m should be a build to sprint",
      "Start at 80% effort for first 100m, build to sprint for the remainder",
      "Record splits",
    ],
  },
  {
    week: 9, day: 4, type: "engine_builder", phase: "peak",
    title: "Open Engine",
    duration: "Every 5:00 Minutes x 6",
    workout: [
      "Every 5:00 Minutes x 6",
      "10/8 Cal Bike",
      "50ft/12.5m Sled Push",
      "200m Run",
      "Rest in time remaining",
    ],
    notes: [
      "Focus on running immediately after the sled push and on speed/turnover of your legs",
      "The runs won't feel fast but see what your legs can do while compromised",
    ],
  },
  {
    week: 9, day: 5, type: "race_sim", phase: "peak",
    title: "Open Complete",
    duration: "For Time",
    workout: [
      "For Time:",
      "40-25-15",
      "Cal Bike",
      "Wall Balls (14/10lbs or 6/4kg)",
      "Goblet Lunge",
      "DB Push Press (53/35lbs x 2)",
      "*800m Run after each round",
    ],
    notes: [
      "Steady pace throughout",
      "Record 800m run splits to see variance per round",
    ],
  },
  // ── WEEK 10 (PEAK) ──────────────────────────────────────────────
  {
    week: 10, day: 1, type: "engine_builder", phase: "peak",
    title: "Open Engine",
    duration: "6 Rounds",
    workout: [
      "6 Rounds:",
      "400m Run",
      "25 Reps*",
      "2:00 Minutes Rest",
      "*Round 1: Wall Balls (14/10lbs or 6/4kg)",
      "*Round 2: DB Lunge (35/20lbs or 15/7.5kg x 2)",
      "*Round 3: DB Front Squat (35/20lbs or 15/7.5kg x 2)",
      "*Rounds 4-6: Repeat",
    ],
    notes: [
      "Focus is on run speed",
      "Record splits for each, try to stay consistent but aim for faster than race pace",
      "Do 25 reps of the corresponding movement immediately after the run",
      "You will go through each movement 2x total",
      "2:00 Minutes rest after each round",
    ],
  },
  {
    week: 10, day: 2, type: "race_sim", phase: "peak",
    title: "Open Complete",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "1000m Run",
      "100ft/25m Sled Push",
      "40 Back Rack Walking Lunge",
    ],
    notes: [
      "1000m runs should feel like race effort",
      "Sled Push should be AHAP (As Heavy As Possible)",
      "For lunges, choose any way to add weight on back (Sandbag, barbell, etc)",
      "If using a barbell, go heavy enough that you'd break after 20 reps",
    ],
  },
  {
    week: 10, day: 3, type: "engine_builder", phase: "peak",
    title: "Open Engine",
    duration: "6 x 400m Run HARD",
    workout: [
      "6 x 400m Run HARD",
      "2:00 Minutes rest after each Run",
    ],
    notes: [
      "Don't hold back on these 400m runs",
      "See where you can hang and where you fall off",
      "Record Splits",
    ],
  },
  {
    week: 10, day: 4, type: "engine_builder", phase: "peak",
    title: "Open Engine",
    duration: "5 Rounds",
    workout: [
      "5 Rounds:",
      "12/10 Cal Bike",
      "8 Burpee Broad Jumps",
      "20 Wall Balls",
      "12/10 Cal Bike",
      "1:00 Minute Rest",
    ],
    notes: [
      "Each round is an 80-100% effort",
      "Wall Balls should be unbroken",
      "PUSH on the bike but pay attention to RPM and don't fall off",
      "Adjust weight as needed throughout",
    ],
  },
  {
    week: 10, day: 5, type: "race_sim", phase: "peak",
    title: "Open Complete",
    duration: "For Time",
    workout: [
      "For Time:",
      "1000m Ski",
      "1000m Row",
      "1000m Run",
      "75 Goblet Squat (53/35lbs or 24/16kg)",
      "75 KBS (53/35lbs or 24/16kg)",
      "50 Headcutters",
      "50 Burpee Broad Jump",
      "50 Cal Bike",
      "100m Sled Push",
    ],
    notes: [
      "Partition reps in any way, in any order",
      "Goal is completion in 60 minutes or less",
      "Use the same KB weight throughout",
    ],
  },
  // ── WEEK 11 (PEAK) ──────────────────────────────────────────────
  {
    week: 11, day: 1, type: "race_sim", phase: "peak",
    title: "Open Complete",
    duration: "3 RFT",
    workout: [
      "3 RFT:",
      "35/20 Cal Bike",
      "400m Run",
      "30 Sandbag Lunge",
      "500m Ski",
      "100m Farmers Carry (53/35lbs or 24/16kg x 2)",
    ],
    notes: [
      "Watch RPM on bike and stay consistent",
      "If no sandbag, use DB or Barbell on back",
      "100m Farmer Carry should be unbroken",
    ],
  },
  {
    week: 11, day: 2, type: "stations", phase: "peak",
    title: "Open Foundation",
    duration: "25 Min AMRAP",
    workout: [
      "25 Min AMRAP:",
      "100ft/25m Sled Push",
      "500m Run or Row",
      "20 Wall Balls (14/10lbs or 6/4kg)",
    ],
    notes: [
      "This should be a moderate Recovery Pace",
      "Stay steady and consistent",
      "Run or Row, depending on what you're feeling for the day",
    ],
  },
  {
    week: 11, day: 3, type: "engine_builder", phase: "peak",
    title: "Open Engine",
    duration: "4 x 800m Run at Race Pace",
    workout: [
      "4 x 800m Run at Race Pace",
      "2:00 Minutes rest after each Run",
    ],
    notes: [
      "These should feel fresh",
      "Run at what you feel is race pace",
      "Record Splits",
    ],
  },
  {
    week: 11, day: 4, type: "recovery", phase: "peak",
    title: "Open Aerobic",
    duration: "45-60 Minutes Run",
    workout: [
      "45-60 Minutes Run",
      "6 x 1:00 Minutes Pickup",
      "2 Minutes Easy between each Run",
    ],
    notes: [
      "FOUNDATION 6 x 1 Minutes Pick Up/2 Minutes Easy at some point during the run",
      "The pickup can be hard or moderate depending on how you're feeling",
    ],
  },
  {
    week: 11, day: 5, type: "race_sim", phase: "peak",
    title: "Open Complete",
    duration: "5 Rounds",
    workout: [
      "5 Rounds:",
      "800m Run",
      "*Choose 5 HYROX Stations you'd like to run through",
    ],
    notes: [
      "Choose any 5 HYROX Race Movement Standards",
      "Go in race order",
      "Goal should be race pace or race feel",
    ],
  },
  // ── WEEK 12 (TAPER) ──────────────────────────────────────────────
  {
    week: 12, day: 1, type: "stations", phase: "taper",
    title: "Open Foundation",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "500m Row",
      "20 KB Deadlift (53/35lbs or 24/16kg x 2)",
      "100m Farmer Carry (53/35lbs or 24/16kg x 2)",
      "50ft/12.5 Sled Pull",
    ],
    notes: [
      "Moderate Pace",
      "Practice different types of sled pull technique: arms only, full body, walk back",
      "Go lighter on KB Deadlift and Farmer Carry if you want to lower the intensity",
    ],
  },
  {
    week: 12, day: 2, type: "recovery", phase: "taper",
    title: "Open Aerobic",
    duration: "40 Min AMRAP",
    workout: [
      "40 Min AMRAP",
      "Machine Cals:",
      "10-15-20-25-30-etc",
      "Rotate between Ski/Bike + Row",
    ],
    notes: [
      "Moderate Pace",
      "Go by feel, if you feel good and want to add intensity",
      "Do the first 10 Cals of each movement as a sprint or hard effort followed by recovery",
    ],
  },
  {
    week: 12, day: 3, type: "engine_builder", phase: "taper",
    title: "Open Engine",
    duration: "6x",
    workout: [
      "6x",
      "200m Build to sprint",
      "6 Burpee Broad Jump",
      "1:00 Minute Rest",
    ],
    notes: [
      "These should feel fresh",
      "Build to a sprint",
      "Adjust the number of Burpee Broad Jumps as desired",
    ],
  },
  {
    week: 12, day: 4, type: "recovery", phase: "taper",
    title: "Open Aerobic",
    duration: "45 Minutes Easy Run",
    workout: [
      "45 Minutes Easy Run",
    ],
    notes: [
      "This should be a \"Feel good\" Jog.",
      "Option to switch to Row, Ski or Bike",
    ],
  },
  {
    week: 12, day: 5, type: "recovery", phase: "taper",
    title: "Open Aerobic",
    duration: "20-30 Minutes Shake Out Run",
    workout: [
      "Optional:",
      "20-30 Minutes Shake Out Run",
    ],
    notes: [
      "Totally optional depending on how you're feeling",
      "Only if you think your legs will benefit from a quick/easy run",
      "Don't stress about getting it in",
    ],
  },
]

// Source: docs/hyrox-source/pro.md
export const PRO_PLAN_SESSIONS: RawSession[] = [
  // ── WEEK 1 (BASE) ──────────────────────────────────────────────
  {
    week: 1, day: 1, type: "stations", phase: "base",
    title: "Pro Foundation",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "500m Row",
      "15 KB Deadlifts (70/53lbs or 32/24kg x 2)",
      "20 Wall Balls (20/14lbs or 9/6kg)",
      "100m Farmer Carry (70/53lbs or 32/24kg x 2)",
    ],
    notes: [
      "Pay attention to pace on row, stay consistent",
      "KB Deadlifts should be heavy but done in 1 set",
      "Wall Balls should be unbroken",
      "Go heavier on Farmers Carry if desired",
    ],
  },
  {
    week: 1, day: 2, type: "recovery", phase: "base",
    title: "Pro Aerobic",
    duration: "45-60 Minutes Run",
    workout: [
      "45-60 Minutes Run",
      "Finish with 6x 20 Second Strides",
    ],
    notes: [
      "Conversational pace",
      "During strides, start slow and build to sprint effort for the last 6-10 steps",
    ],
  },
  {
    week: 1, day: 3, type: "stations", phase: "base",
    title: "Pro Foundation",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "50ft Sled Push - AHAP",
      "400m Run",
      "15 Headcutters (70/53lbs or 32/24kg)",
    ],
    notes: [
      "AHAP = As Heavy As Possible",
      "Headcutters should be heavy enough where you may need to break into 2 sets",
    ],
  },
  {
    week: 1, day: 4, type: "stations", phase: "base",
    title: "Pro Power",
    duration: "Quality Sets",
    workout: [
      "4x",
      "Goblet Squat x 20",
      "DB Bench Press x 15",
      "Chin Ups x Failure",
      "Max Bike Sprint x 30 sec",
      "90 sec Rest",
      "4x",
      "Bulgarian Split Squats x 10 Each Leg",
      "DB Shoulder Press x 15",
      "(redacted in source)",
      "DB Curls x 12 Each",
      "200m Loaded Carry (100m Front Rack/100m Farmers Carry)",
    ],
    notes: [
      "This is for quality, not for time",
      "Choose weights where the last 3 reps are very challenging",
      "If unable to do chin ups, do TRX or Ring Rows",
      "Movements are meant to be done one after the other with minimal rest. Rest 90 seconds after each round",
      "On the loaded carry, use the same weight for both. Hold KBs or DBs in front rack position for the first 100m, then switch to a farmer carry hold for the second 100m",
      "Rest as needed throughout",
    ],
  },
  {
    week: 1, day: 5, type: "stations", phase: "base",
    title: "Pro Foundation",
    duration: "For Time: 3 Rounds",
    workout: [
      "For Time: 3 Rounds",
      "800m-400m-200m Run",
      "30-20-10",
      "Alt DB Snatch",
      "(redacted in source)",
      "Goblet Lunge",
      "50ft/12.5m Sled Push after each round",
    ],
    notes: [
      "Workout is 3 rounds total, with descending reps each round (Sled Push remains the same throughout)",
      "Round 1: 800m Run and 30 reps of each Movement",
      "Round 2: 400m Run and 20 reps of each Movement",
      "Round 3: 200m Run and 10 reps of each Movement",
    ],
  },
  // ── WEEK 2 (BASE) ──────────────────────────────────────────────
  {
    week: 2, day: 1, type: "stations", phase: "base",
    title: "Pro Foundation",
    duration: "25 Min AMRAP",
    workout: [
      "25 Min AMRAP:",
      "5-10-15-20-25-etc",
      "KB Deadlift (70/53lbs or 32/24kg x 2)",
      "KB/DB Front Rack Lunge (70/53lbs or 32/24kg x 2)",
      "10-20-30-40-50-etc",
      "Wall Balls (20/14lbs or 9/6kg)",
      "*200m Run after each Round",
    ],
    notes: [
      "Continue up the ladder until you reach 25 minutes",
      "200m Run does not change throughout",
      "Round 1: 5 KB DL/5 FR Lunge/10 Wallballs/200m Run",
      "Round 2: 10 KB DL/10 FR Lunge/20 Wallballs/200m Run",
      "Round 3: 15 KB DL/15 FR Lunge/30 Wallballs/200m Run — etc",
    ],
  },
  {
    week: 2, day: 2, type: "recovery", phase: "base",
    title: "Pro Aerobic",
    duration: "50-60 Minutes",
    workout: [
      "50-60 Minutes:",
      "5:00 Minute Bike",
      "5:00 Minute Row",
      "5:00 Minute Ski",
    ],
    notes: [
      "Work for 50-60 minutes total",
      "Pay attention to pace throughout and stay consistent",
      "Conversational pace, but you should break a sweat",
    ],
  },
  {
    week: 2, day: 3, type: "stations", phase: "base",
    title: "Pro Foundation",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "400m Run",
      "10 DB Thruster (50/35lbs or 22.5/17.5 kg x 2)",
      "12 Burpee Broad Jump",
    ],
    notes: [
      "DB Thrusters should be unbroken, but they should be heavy enough where you couldn't do 5 more",
      "Plant hands close to feet in order to maintain the Burpee Broad Jump standard",
    ],
  },
  {
    week: 2, day: 4, type: "stations", phase: "base",
    title: "Pro Power",
    duration: "Quality Sets",
    workout: [
      "For 16 Minutes:",
      "100 Cal Row",
      "Every 2:00 Minutes 10 x Bench Press",
      "4x",
      "25 Back Squats (Unbroken)",
      "10 Cal Bike Sprint",
      "2:00 Minutes Rest after each round",
      "400m Suitcase Carry (Switch arms as needed)",
    ],
    notes: [
      "100 Cal Row should be a moderate pace",
      "Stop every 2 Minutes and Foundation 10 x Bench Press. (Build each round)",
      "Back squats should be unbroken, build each round",
      "Go immediately into the 10 Cal Bike Sprint",
      "Suitcase Carry: Switch arms as needed but don't come to a Foundation stop at any point",
    ],
  },
  {
    week: 2, day: 5, type: "stations", phase: "base",
    title: "Pro Foundation",
    duration: "For Time",
    workout: [
      "For Time:",
      "30-20-10",
      "Alt DB Snatch",
      "50ft/12.5m Sled Pull (Arms Only)",
      "*200m Farmers Carry after each round (70/53lbs or 32/24kg x 2)",
    ],
    notes: [
      "3 Rounds total",
      "DB Snatch reps decrease each round",
      "Sled Pull should be AHAP, no walking back",
      "Farmer Carry should be heavy enough where you need to break at least 1 time during each 200m",
    ],
  },
  // ── WEEK 3 (BASE) ──────────────────────────────────────────────
  {
    week: 3, day: 1, type: "stations", phase: "base",
    title: "Pro Foundation",
    duration: "For Time",
    workout: [
      "For Time:",
      "50-40-30-20-10",
      "Wall Balls (20/14lbs or 9/6kg)",
      "21-18-15-12-9",
      "KBS (70/53lbs or 32/24kg)",
      "*400m Run after each round",
      "*Every time you break on Wall Balls, Foundation 10 Burpees",
    ],
    notes: [
      "5 Rounds, reps decrease each round",
      "400m Run remains the same",
      "A break on Wall Balls is any time movement stops or ball drops",
      "Round 1: 50 Wall Balls/21 KBS/400m Run",
      "Round 2: 40 Wall Balls/18 KBS/400m Run",
      "Round 3: 30 Wall Balls/15 KBS/400m Run — etc",
      "(+ penalty burpees if you break on wall balls)",
    ],
  },
  {
    week: 3, day: 2, type: "recovery", phase: "base",
    title: "Pro Aerobic",
    duration: "50 Minutes Progressive Run",
    workout: [
      "50 Minutes Progressive Run",
      "Increase pace every 10 Minutes so last 10 Minutes is fastest/hardest effort",
    ],
    notes: [
      "If you have a GPS watch, use it and take splits to record data",
      "The last 10 mins should feel harder than race effort",
    ],
  },
  {
    week: 3, day: 3, type: "stations", phase: "base",
    title: "Pro Foundation",
    duration: "For Time",
    workout: [
      "For Time:",
      "100m Farmer Carry",
      "21-18-15-12-9-6-3",
      "DB Hang Clean*",
      "DB Push Press*",
      "DB Front Squat*",
      "*(50/35lbs or 22.5/17.5 kg x 2)",
    ],
    notes: [
      "7 Rounds total",
      "Each round starts with a 100m Farmer Carry",
      "This will be grippy!",
      "Use the same weight throughout for all movements",
    ],
  },
  {
    week: 3, day: 4, type: "stations", phase: "base",
    title: "Pro Power",
    duration: "Quality Sets",
    workout: [
      "4x",
      "Barbell RDL x 8",
      "DB Split Squat Jump x 10",
      "100ft/25m Sled Sprint",
      "1:30 Minutes Rest",
      "4x",
      "Bench Press x 20",
      "KBS x 20",
      "10 Cal Ski Sprint",
      "1:30 Minutes Rest",
    ],
    notes: [
      "For quality, not for time",
      "Build RDL weight",
      "DBs should be light for Split Squat Jump",
      "Sled Push: Use 50% of the weight you normally use in training",
      "Rest after each Foundation round",
      "Bench Press: Build each round",
      "Movements should be back to back with rest after each round",
    ],
  },
  {
    week: 3, day: 5, type: "stations", phase: "base",
    title: "Pro Foundation",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "20 DB Front Rack Lunge (50/35lbs or 22.5/17.5 kg x 2)",
      "15 HR Push Ups",
      "10 Cal Ski",
      "3 Wall Walks",
    ],
    notes: [
      "Lunges should be unbroken",
      "Push Ups should be STRICT: No sagging core, hips and shoulders in line",
      "HR = Hand Release at bottom of push up",
      "Wall Walks:",
      "Start on ground with feet against wall.",
      "Push up and walk hands towards the wall and feet up the wall.",
      "Don't arch back, keep neutral pelvis",
      "Get nose as close to the wall as possible while maintaining technique",
    ],
  },
  // ── WEEK 4 (BASE) ──────────────────────────────────────────────
  {
    week: 4, day: 1, type: "race_sim", phase: "base",
    title: "Pro Complete",
    duration: "For Time",
    workout: [
      "For Time:",
      "30-20-10",
      "DB Push Press (50/35lbs or 22.5/17.5kg x 2)",
      "10-10-10",
      "Strict Pull Up",
      "30-20-10",
      "Alt DB Snatch",
      "*800m Run after each Round",
    ],
    notes: [
      "3 Rounds, decrease reps EXCEPT Strict Pull Ups and 800m Run remain the same",
      "Sub inverted bar rows for strict pull ups if needed",
      "Round 1: 30 DB Push Press/10 Strict Pull Ups/30 Alt DB Snatch/800m Run",
      "Round 2: 20 DB Push Press/10 Strict Pull Ups/20 Alt DB Snatch/800m Run etc",
    ],
  },
  {
    week: 4, day: 2, type: "engine_builder", phase: "base",
    title: "Pro Engine",
    duration: "1 Mile Run Warm Up",
    workout: [
      "1 Mile Run Warm Up",
      "12 x 200m Runs at 90% Effort",
      "1:00 Minute Easy Jog between Runs",
      "1 Mile Cool Down",
    ],
    notes: [
      "Each effort should be a build to 90% effort",
      "Focus on quick turnover",
      "Recovery jog should be super slow/easy if not walk",
    ],
  },
  {
    week: 4, day: 3, type: "stations", phase: "base",
    title: "Pro Foundation",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "400m Ski/Row",
      "400m Run",
      "100ft/25m Sled Push AHAP",
    ],
    notes: [
      "Ski/Row: Moderate Pace",
      "Run: Race Pace",
      "Sled Push: Sled should be As Heavy As Possible",
    ],
  },
  {
    week: 4, day: 4, type: "recovery", phase: "base",
    title: "Pro Aerobic",
    duration: "4x",
    workout: [
      "4x",
      "Split Squat x 10 each",
      "KB Deadlift x 20",
      "DB Bench Press x 20",
      "1:00 Minute Rest",
      "4x",
      "10 Cal Ski",
      "5-8 Strict Pull Ups",
      "50ft/12.5m Sled Pull",
      "1:00 Minute Rest",
    ],
    notes: [
      "For Quality, not for time",
      "Split Squat: Foundation all 10 reps on one leg before switching to the other. Feet should remain planted in lunge for entirety of set",
      "KB Deadlift and DB Bench Press should be unbroken",
      "Modify strict pull ups to inverted bar rows if needed",
      "Sled Pull should be arms only",
      "Rest at the end of each round",
    ],
  },
  {
    week: 4, day: 5, type: "stations", phase: "base",
    title: "Pro Foundation",
    duration: "30 Minutes AMRAP",
    workout: [
      "30 Minutes AMRAP:",
      "3-6-9-12-15-etc",
      "KBS (70/53lbs or 32/24 kg)",
      "Headcutter (70/53lbs or 32/24 kg)",
      "Burpee Broad Jump",
      "*10 Cal Sprint after each round (any machine)",
    ],
    notes: [
      "Continue ascending rep ladder until 30 mins are up",
      "Each movement (except for Cals) should increase by 3 reps each round",
      "Each round should end with a 10 Cal Sprint",
      "Round 1: 3 KBS/3 Headcutter/3 Burpee Broad Jump/10 Cal Sprint",
      "Round 2: 6 KBS/6 Headcutter/6 Burpee Broad Jump/10 Cal Sprint",
      "Round 3: 9 KBS/9 Headcutter/9 Burpee Broad Jump/10 Cal Sprint",
      "… etc",
    ],
  },
  // ── WEEK 5 (BUILD) ──────────────────────────────────────────────
  {
    week: 5, day: 1, type: "stations", phase: "build",
    title: "Pro Foundation",
    duration: "For Time",
    workout: [
      "For Time:",
      "30-25-20-15-10",
      "Cal Ski",
      "HR Push Ups",
      "DB Push Press (50/35lbs or 22.5/17.5 kg x 2)",
      "KB Deadlift (50/35lbs or 22.5/17.5 kg x 2)",
    ],
    notes: [
      "Push Ups should be STRICT: No sagging core, hips and shoulders in line",
      "HR = Hand Release at bottom of push up",
      "Option to go heavier on KB Deadlift",
      "Expect to break up sets",
    ],
  },
  {
    week: 5, day: 2, type: "engine_builder", phase: "build",
    title: "Pro Engine",
    duration: "6 x 4 Min AMRAP",
    workout: [
      "6 x 4 Min AMRAP:",
      "4:00 Minutes on/2:00 Minutes off",
      "400m Run",
      "12 Headcutters (70/53lbs or 32/24 kg)",
      "Max Cal Bike",
    ],
    notes: [
      "Each round should be a build to a 90% effort",
      "Goal is pacing and consistency across rounds",
      "Headcutters should be unbroken",
      "Score = Number of Cals",
    ],
  },
  {
    week: 5, day: 3, type: "recovery", phase: "build",
    title: "Pro Aerobic",
    duration: "E2MOM",
    workout: [
      "E2MOM:",
      "5000 Meters Row",
      "5 x Burpee Over Rower",
    ],
    notes: [
      "Starting at 0:00, Foundation 5 Burpees over the rower",
      "Continue rowing until you reach 5000m while stopping every 2 minutes on the minute to do 5 Burpees over the rower",
    ],
  },
  {
    week: 5, day: 4, type: "engine_builder", phase: "build",
    title: "Pro Engine",
    duration: "6 x 400m Run",
    workout: [
      "6 x 400m Run",
      "2:00 Minutes Rest after each Run",
    ],
    notes: [
      "Each 400m should be faster than race pace",
      "Record each 400m split",
      "Log results and note changes in pace, what you are able to hold, etc.",
      "The goal should be to find what pace you can maintain without leaving anything in the tank",
    ],
  },
  {
    week: 5, day: 5, type: "race_sim", phase: "build",
    title: "Pro Complete",
    duration: "For Time",
    workout: [
      "For Time:",
      "1000 Meters Row/Ski",
      "4x",
      "150ft DB Lunge (50/35lbs or 22.5/17.5 kg x 2)",
      "25 Wall Balls (20/14lbs or 9/6kg)",
      "400m Run",
      "100/75 Cal Bike",
      "*Accumulate 350ft/100m Sled Push throughout",
    ],
    notes: [
      "The 1000m Row or Ski is to be done once as a buy in",
      "The 100/75 Cal Bike is to be done once as a cash out",
      "DB Lunges can be done as Front Rack or to your sides",
      "The Sled Push can be broken up in any way throughout",
      "Weight on the sled should be AHAP (As Heavy As Possible)",
    ],
  },
  // ── WEEK 6 (BUILD) ──────────────────────────────────────────────
  {
    week: 6, day: 1, type: "stations", phase: "build",
    title: "Pro Foundation",
    duration: "3 RFT",
    workout: [
      "3 RFT:",
      "200m Farmer Carry (70/53lbs or 32/24kg x 2)",
      "15 KBS (70/53lbs or 32/24kg)",
      "30 Goblet Squat (70/53lbs or 32/24kg)",
      "400 Meters Ski or Row",
    ],
    notes: [
      "Use the same weight throughout: 1 KB for KBS and Goblet Squat/2 KBs for Farmers Carry",
      "Farmers Carry weight should be heavy enough where you need to set the KBs down 1-2 times",
    ],
  },
  {
    week: 6, day: 2, type: "engine_builder", phase: "build",
    title: "Pro Engine",
    duration: "20 Minutes Alt EMOM (50 sec on/10 sec off)",
    workout: [
      "20 Minutes Alt EMOM (50 sec on/10 sec off)",
      "Front Rack KB Lunge (53/35lbs or 24/16kg x 2)",
      "Strict Pull Ups/Push Ups",
      "200 Meters Run",
      "Rest",
    ],
    notes: [
      "Alternate movements each minute",
      "Work 50 seconds, use the 10 seconds rest to transition",
      "Do a max set of strict pull ups followed by push ups in the time remaining",
      "If you are unable to do strict pull ups, do push ups only",
    ],
  },
  {
    week: 6, day: 3, type: "recovery", phase: "build",
    title: "Pro Aerobic",
    duration: "60 Minutes Run",
    workout: [
      "60 Minutes Run",
      "Within the 60 Minutes window, Foundation 2x 15 Min Pick Ups",
    ],
    notes: [
      "The 15 Minute pick ups can be done at any time",
      "Pace should be lactate threshold hold, or a pace you can maintain for 15 minutes just below the point of discomfort",
    ],
  },
  {
    week: 6, day: 4, type: "engine_builder", phase: "build",
    title: "Pro Engine",
    duration: "3 Rounds: 1:00 Minute on/1:00 Minute off",
    workout: [
      "3 Rounds: 1:00 Minute on/1:00 Minute off",
      "Sled Push",
      "Sled Pull",
      "DB Box Over",
      "Headcutter (70/53lbs or 32/24kg x 2)",
      "Push Ups",
    ],
    notes: [
      "1 Minute at each movement station",
      "Alternate movements",
      "1 Minute rest between each",
      "You should be working HARD the entirety of the minute",
    ],
  },
  {
    week: 6, day: 5, type: "race_sim", phase: "build",
    title: "Pro Complete",
    duration: "For Time",
    workout: [
      "For Time:",
      "100/75 Cal Bike or Ski",
      "100 Back Squat (135/95lbs or 60/45kg)",
      "1 Mile Run",
      "100 KBS (53/35lbs or 24/16kg)",
      "100/75 Cal Bike or Ski",
      "100 Headcutters (53/35lbs or 24/16kg)",
      "*Every break complete 100m Farmer Carry (70/53lbs or 32/24kg x 2)",
    ],
    notes: [
      "Back Squats: Choose a weight that you can get at least a set of 30 unbroken while fresh",
      "KBS and Headcutter weight should be slightly lighter than usual",
      "Every time you break, complete 100m Farmers Carry (Only applies for back squat, KBS, and Headcutters)",
      "It is considered a break on back squats if you put the bar down",
      "It is considered a break on KBS and Headcutters if movement stops",
    ],
  },
  // ── WEEK 7 (BUILD) ──────────────────────────────────────────────
  {
    week: 7, day: 1, type: "stations", phase: "build",
    title: "Pro Foundation",
    duration: "For Time",
    workout: [
      "For Time:",
      "30-25-20-15",
      "KB Deadlift (70/53lbs or 32/24kg x 2)",
      "DB/KB Lunge (53/35lbs or 24/16kg x 2)",
      "Headcutter (70/53lbs or 32/24kg)",
      "100m Farmers Carry (70/53lbs or 32/24kg x 2)",
    ],
    notes: [
      "Weight should be the same for KB Deadlift and Farmer Carry",
      "Lunges can be done with a front rack hold or to the sides",
      "Headcutter: Use one of the KBs you used for the Farmers Carry and Deadlift",
    ],
  },
  {
    week: 7, day: 2, type: "engine_builder", phase: "build",
    title: "Pro Engine",
    duration: "5 x 3:00 Minutes AMRAP: 3:00 on/3:00 off",
    workout: [
      "5 x 3:00 Minutes AMRAP: 3:00 on/3:00 off",
      "10 Devils Press (53/35lbs or 24/16kg x 2)",
      "6 Burpee Box Jump Over",
      "Max Cal Bike",
    ],
    notes: [
      "Devils Press should be done in 1:30 Minute or less (lower reps if needed)",
      "Each round should be a sprint effort",
      "Goal is to find a pace where you can go HARD but maintain while having a 1:1 work/rest ratio",
      "Score = Cals (stay consistent)",
    ],
  },
  {
    week: 7, day: 3, type: "engine_builder", phase: "build",
    title: "Pro Engine",
    duration: "4 x 1000m Run at Race Pace",
    workout: [
      "4 x 1000m Run at Race Pace",
      "2 Minutes Rest after each",
    ],
    notes: [
      "Record each 1000m Split",
      "Log results and note changes in pace, what you are able to hold, etc.",
      "The goal should be to find what pace you can maintain without leaving anything in the tank",
    ],
  },
  {
    week: 7, day: 4, type: "stations", phase: "build",
    title: "Pro Foundation",
    duration: "0:00 - 12:00 Minutes AMRAP",
    workout: [
      "0:00 - 12:00 Minutes AMRAP:",
      "15 Wall Balls (20/14lbs or 9/6kg)",
      "12 DB Push Press (53/35lbs or 24/16kg x 2)",
      "9 Cal Ski",
      "200m Run",
      "12:00 - 22:00 // AMRAP:",
      "50ft/12.5m Sled Push AHAP",
      "22:00 - 30:00 // AMRAP:",
      "8 Headcutters (70/53lbs or 32/24kg)",
      "10 Burpees",
    ],
    notes: [
      "Each AMRAP goes immediately into the next",
      "Sled Push should be AHAP (As Heavy As Possible)",
      "Focus on going right into the run",
      "Rest if needed AFTER the run, not between sled and run",
      "Headcutters should be done unbroken",
    ],
  },
  {
    week: 7, day: 5, type: "race_sim", phase: "build",
    title: "Pro Complete",
    duration: "3x",
    workout: [
      "3x",
      "30/20 Cal Bike",
      "100ft/25m Sled Push (AHAP)",
      "50ft/12.5m BBJ",
      "400m Run",
      "Into:",
      "3x",
      "30/20 Cal Ski",
      "20 KB Deadlift (70/53lbs or 32/24kg x 2)",
      "100m Farmers Carry (70/53lbs or 32/24kg x 2)",
      "25 Wall Balls (20/14lbs or 9/6kg)",
    ],
    notes: [
      "Focus on consistent and steady pace throughout BBJ",
      "KB Deadlift and Farmers Carry weight should be the same",
      "Go unbroken on Wall Balls",
    ],
  },
  // ── WEEK 8 (BUILD) ──────────────────────────────────────────────
  {
    week: 8, day: 1, type: "stations", phase: "build",
    title: "Pro Foundation",
    duration: "5 RFT",
    workout: [
      "5 RFT:",
      "50ft/12.5m Sled Pull",
      "12 Alt DB Snatch (53/35lbs or 24/16kg)",
      "25 Wall Balls (14/10lbs or 6/4 kg)",
      "200m Ski",
    ],
    notes: [
      "Sled Pull: Practice both walk back method and arms only. Adjust weight as needed",
      "Wall Balls should be unbroken",
    ],
  },
  {
    week: 8, day: 2, type: "engine_builder", phase: "build",
    title: "Pro Engine",
    duration: "E2MOM x 10",
    workout: [
      "E2MOM x 10",
      "50ft/12.5m Sled Push",
      "200m Sprint",
      "Rest in time remaining",
    ],
    notes: [
      "The focus is getting used to running immediately after the sled",
      "Run what \"feels\" like a sprint after the sled push",
    ],
  },
  {
    week: 8, day: 3, type: "engine_builder", phase: "build",
    title: "Pro Engine",
    duration: "8 x 400m Run",
    workout: [
      "8 x 400m Run",
      "2 Minutes Rest after each",
    ],
    notes: [
      "Challenge yourself to see what you're capable of",
      "Push the pace on these 400m Runs",
      "Keep track of your splits and see where you fall off",
      "Goal should be to find your breaking point",
    ],
  },
  {
    week: 8, day: 4, type: "engine_builder", phase: "build",
    title: "Pro Engine",
    duration: "Every 3:30 Minutes x 5",
    workout: [
      "Every 3:30 Minutes x 5",
      "30 Wall Balls",
      "200m Sprint",
      "Rest in time remaining",
    ],
    notes: [
      "Focus is SPEED",
      "Wall Balls unbroken",
      "No rest, immediately into the 200m Sprint",
    ],
  },
  {
    week: 8, day: 5, type: "race_sim", phase: "build",
    title: "Pro Complete",
    duration: "3 RFT",
    workout: [
      "3 RFT:",
      "500m Ski/Row",
      "100ft/25m Goblet Lunge (53/35lbs or 24/16kg)",
      "100m Farmers Carry (70/53lbs or 32/24kg x 2)",
      "1000m Run",
      "*Accumulate 350ft or 100m Sled Push or Pull throughout",
    ],
    notes: [
      "Lunges can be front rack hold or KB/DBs to your sides",
      "Sled Push or Pull can be broken up throughout, as long as you reach the designated distance total",
    ],
  },
  // ── WEEK 9 (PEAK) ──────────────────────────────────────────────
  {
    week: 9, day: 1, type: "engine_builder", phase: "peak",
    title: "Pro Engine",
    duration: "5 Rounds",
    workout: [
      "5 Rounds:",
      "500m Run",
      "*Movement",
      "2:00 Minutes Rest",
      "Round 1: 500m Ski",
      "Round 2: 40 BBJs",
      "Round 3: 200m Farmers Carry (70/53lbs or 32/24kg x 2)",
      "Round 4: 50 Sandbag Lunge (30/20kg)",
      "Round 5: 75 Wall Balls (20/14lbs or 9/6kg)",
    ],
    notes: [
      "Focus is on run pace",
      "Each round starts with a 500m Run",
      "Take splits of each run",
      "Each run should feel like a race pace effort",
      "The movement will change each round",
      "Do the movement that corresponds to the round",
    ],
  },
  {
    week: 9, day: 2, type: "race_sim", phase: "peak",
    title: "Pro Complete",
    duration: "For Time",
    workout: [
      "For Time:",
      "50-40-30-20-10",
      "Cal Ski",
      "DB Push Press (50/35lbs or 22.5/17.5kg)",
      "Alt DB Snatch (50/35lbs or 22.5/17.5kg)",
      "DB Front Squat (50/35lbs or 22.5/17.5kg)",
    ],
    notes: [
      "Steady pace",
      "Break up DB Movements as needed",
    ],
  },
  {
    week: 9, day: 3, type: "engine_builder", phase: "peak",
    title: "Pro Engine",
    duration: "12 x 200m Run Max Effort",
    workout: [
      "12 x 200m Run Max Effort",
      "1:30 Minute Rest after each",
    ],
    notes: [
      "Each 200m should be a build to sprint",
      "Start at 80% effort for first 100m, build to sprint for the remainder",
      "Record splits",
    ],
  },
  {
    week: 9, day: 4, type: "engine_builder", phase: "peak",
    title: "Pro Engine",
    duration: "Every 5:00 Minutes x 6",
    workout: [
      "Every 5:00 Minutes x 6",
      "15/10 Cal Bike",
      "50ft/12.5m Sled Push",
      "200m Run",
      "Rest in time remaining",
    ],
    notes: [
      "Focus on running immediately after the sled push and on speed/turnover of your legs",
      "The runs won't feel fast but see what your legs can do while compromised",
    ],
  },
  {
    week: 9, day: 5, type: "race_sim", phase: "peak",
    title: "Pro Complete",
    duration: "For Time",
    workout: [
      "For Time:",
      "50-30-10",
      "Cal Bike",
      "Wall Balls (20/14lbs or 9/6kg)",
      "Dual KB Front Rack Lunge (53/35lbs or 24/16kg x 2)",
      "DB Push Press (50/35lbs or 22.5/17.5kg x 2)",
      "*800m Run after each round",
    ],
    notes: [
      "Steady pace throughout",
      "Record 800m run splits to see variance per round",
    ],
  },
  // ── WEEK 10 (PEAK) ──────────────────────────────────────────────
  {
    week: 10, day: 1, type: "engine_builder", phase: "peak",
    title: "Pro Engine",
    duration: "8 Rounds",
    workout: [
      "8 Rounds:",
      "400m Run",
      "25 Reps*",
      "2:00 Minutes Rest",
      "*Round 1: Wall Balls (20/14lbs or 9/6kg)",
      "*Round 2: DB Lunge",
      "*Round 3: KB Deadlift",
      "*Round 4: DB Front Squat",
      "*Rounds 5-8: Repeat",
    ],
    notes: [
      "Focus is on run speed",
      "Record splits for each, try to stay consistent but aim for faster than race pace",
      "Do 25 reps of the corresponding movement immediately after the run",
      "You will go through each movement 2x total",
      "2:00 Minutes Rest after each round",
    ],
  },
  {
    week: 10, day: 2, type: "race_sim", phase: "peak",
    title: "Pro Complete",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "1000m Run",
      "100ft/25m Sled Push",
      "40 Back Rack Walking Lunge",
    ],
    notes: [
      "1000m runs should feel like race effort",
      "Sled Push should be AHAP (As Heavy As Possible)",
      "For Lunges, choose any way to add weight on back (Sandbag, barbell, etc)",
      "If using a Barbell, go heavy enough that you'd break after 20 reps",
    ],
  },
  {
    week: 10, day: 3, type: "engine_builder", phase: "peak",
    title: "Pro Engine",
    duration: "6 x 400m Run HARD",
    workout: [
      "6 x 400m Run HARD",
      "2:00 Minutes rest after each Run",
    ],
    notes: [
      "Don't hold back on these 400m runs",
      "See where you can hang and where you fall off",
      "Record Splits",
    ],
  },
  {
    week: 10, day: 4, type: "engine_builder", phase: "peak",
    title: "Pro Engine",
    duration: "5 Rounds",
    workout: [
      "5 Rounds:",
      "15 Cal Bike",
      "10 Burpee Broad Jumps",
      "30 Wall Balls",
      "15 Cal Bike",
      "1:00 Minute Rest",
    ],
    notes: [
      "Each round is an 80-100% effort",
      "Wall Balls should be unbroken",
      "PUSH on the bike but pay attention to RPM and don't fall off",
      "Adjust weight as needed throughout",
    ],
  },
  {
    week: 10, day: 5, type: "race_sim", phase: "peak",
    title: "Pro Complete",
    duration: "For Time",
    workout: [
      "For Time:",
      "1000m Ski",
      "1000m Row",
      "1000m Run",
      "75 Goblet Squat (70/53lbs or 32/24kg)",
      "75 KBS (70/53lbs or 32/24kg)",
      "50 Headcutters",
      "50 Burpee Broad Jump",
      "50 Cal Bike",
      "100m Sled Push",
    ],
    notes: [
      "Partition reps in any way, in any order",
      "Goal is completion in 50 Minutes or less",
      "Use the same KB weight throughout",
    ],
  },
  // ── WEEK 11 (PEAK) ──────────────────────────────────────────────
  {
    week: 11, day: 1, type: "race_sim", phase: "peak",
    title: "Pro Complete",
    duration: "3 RFT",
    workout: [
      "3 RFT:",
      "35 Cal Bike",
      "400m Run",
      "30 Sandbag Lunge (30/20 kg)",
      "500m Ski",
      "100m Farmers Carry (70/53lbs or 32/24kg x 2)",
    ],
    notes: [
      "Watch RPM on bike and stay consistent",
      "If you have no sandbag, use DB or Barbell on back",
      "100m Farmer Carry should be unbroken",
    ],
  },
  {
    week: 11, day: 2, type: "stations", phase: "peak",
    title: "Pro Foundation",
    duration: "25 Min AMRAP",
    workout: [
      "25 Min AMRAP:",
      "100ft/25m Sled Push",
      "500m Run or Row",
      "20 Wall Balls (20/14lbs or 9/6kg)",
    ],
    notes: [
      "This should be a moderate Recovery Pace",
      "Stay steady and consistent",
      "Run or Row, depending on what you're feeling for the day",
    ],
  },
  {
    week: 11, day: 3, type: "engine_builder", phase: "peak",
    title: "Pro Engine",
    duration: "4 x 800m Run at Race Pace",
    workout: [
      "4 x 800m Run at Race Pace",
      "2:00 Minutes rest after each Run",
    ],
    notes: [
      "These should feel fresh",
      "Run at what you feel is race pace",
      "Record Splits",
    ],
  },
  {
    week: 11, day: 4, type: "recovery", phase: "peak",
    title: "Pro Aerobic",
    duration: "40-60 Minutes Run",
    workout: [
      "40-60 Minutes Run",
      "6 x 1:00 Minutes Pickup",
      "2 Minutes Easy between each Run",
    ],
    notes: [
      "Foundation 6 x 1 Minutes Pick Up/2 Minutes Easy at some point during the run",
      "The pickup can be hard or moderate depending on how you're feeling",
    ],
  },
  {
    week: 11, day: 5, type: "race_sim", phase: "peak",
    title: "Pro Complete",
    duration: "5 Rounds",
    workout: [
      "5 Rounds:",
      "800m Run",
      "*Choose 5 HYROX Stations you'd like to run through",
    ],
    notes: [
      "Choose any 5 HYROX Race Movement Standards",
      "Go in race order",
      "Goal should be race pace or race feel",
    ],
  },
  // ── WEEK 12 (TAPER) ──────────────────────────────────────────────
  {
    week: 12, day: 1, type: "stations", phase: "taper",
    title: "Pro Foundation",
    duration: "4 RFT",
    workout: [
      "4 RFT:",
      "500m Row",
      "20 KB Deadlift (70/53lbs or 32/24kg x 2)",
      "100m Farmer Carry (70/53lbs or 32/24kg x 2)",
      "50ft/12.5m Sled Pull",
    ],
    notes: [
      "Moderate Pace",
      "Practice different types of sled pull technique: arms only, full body, walk back",
      "Go lighter on KB Deadlift and Farmer Carry if you want to lower the intensity",
    ],
  },
  {
    week: 12, day: 2, type: "recovery", phase: "taper",
    title: "Pro Aerobic",
    duration: "40 Min AMRAP Machine Cals",
    workout: [
      "40 Min AMRAP Machine Cals:",
      "10-15-20-25-30-etc",
      "Rotate between Ski/Bike + Row",
    ],
    notes: [
      "Moderate Pace",
      "Go by feel, if you feel good and want to add intensity",
      "Do the first 10 Cals of each movement as a sprint or hard effort followed by recovery",
    ],
  },
  {
    week: 12, day: 3, type: "engine_builder", phase: "taper",
    title: "Pro Engine",
    duration: "8x",
    workout: [
      "8x",
      "200m Build to sprint",
      "10 Burpee Broad Jump",
      "1:00 Minute Rest",
    ],
    notes: [
      "These should feel fresh",
      "Build to a sprint",
      "Adjust the number of Burpee Broad Jumps as desired",
    ],
  },
  {
    week: 12, day: 4, type: "recovery", phase: "taper",
    title: "Pro Aerobic",
    duration: "45 Minutes Easy Run",
    workout: [
      "45 Minutes Easy Run",
    ],
    notes: [
      "This should be a \"Feel good\" Jog.",
      "Option to switch to Row, Ski or Bike",
    ],
  },
  {
    week: 12, day: 5, type: "recovery", phase: "taper",
    title: "Pro Aerobic",
    duration: "20-30 Minutes Shake Out Run",
    workout: [
      "Optional:",
      "20-30 Minutes Shake Out Run",
    ],
    notes: [
      "Totally optional depending on how you're feeling",
      "Only if you think your legs will benefit from a quick/easy run",
      "Don't stress about getting it in",
    ],
  },
]
